"""Curated PubMed citations for the evidence library.

All 53 entries verified via PubMed API with confirmed PMIDs, DOIs, and metadata.
Organized by the 6 ACLM pillars of lifestyle medicine.

v2.0 fields: journal_tier (elite/q1/q2/q3/q4) and domain (from RESEARCH_DOMAINS).
"""

EVIDENCE_LIBRARY = [
    # ═══════════════════════════════════════════════════════════════════════
    # PILLAR 1: NUTRITION (pillar_id=1)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "pmid": "29897866", "doi": "10.1056/NEJMoa1800389",
        "title": "Primary Prevention of Cardiovascular Disease with a Mediterranean Diet Supplemented with Extra-Virgin Olive Oil or Nuts",
        "authors": "Estruch R et al.", "journal": "N Engl J Med", "year": 2018,
        "study_type": "rct", "evidence_grade": "B", "pillar_id": 1,
        "summary": "The landmark PREDIMED trial demonstrated that a Mediterranean diet supplemented with extra-virgin olive oil or nuts significantly reduces major cardiovascular events in high-risk individuals.",
        "key_finding": "Mediterranean diet reduced major cardiovascular events by approximately 30% compared to a control diet.",
        "effect_size": "HR 0.69 (95% CI 0.53-0.91) EVOO group; HR 0.72 (95% CI 0.54-0.95) nuts group",
        "sample_size": 7447, "population": "High cardiovascular risk adults",
        "dose_response": None,
        "causation_note": "RCT design supports causal inference; originally retracted and republished with corrections.",
        "tags": "mediterranean_diet,cardiovascular,PREDIMED,olive_oil,nuts",
        "url": "https://pubmed.ncbi.nlm.nih.gov/29897866/",
        "journal_tier": "elite", "domain": "cardio_metabolic",
    },
    {
        "pmid": "35672940", "doi": "10.1111/obr.13462",
        "title": "Effects of vegan diets on cardiometabolic health: A systematic review and meta-analysis of randomized controlled trials",
        "authors": "Termannsen AD et al.", "journal": "Obes Rev", "year": 2022,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 1,
        "summary": "Meta-analysis of 11 RCTs showing vegan diets for 12+ weeks significantly reduce body weight, BMI, HbA1c, total cholesterol, and LDL cholesterol.",
        "key_finding": "Vegan diets reduced body weight by 4.1 kg and HbA1c by 0.18% compared to control diets.",
        "effect_size": "Weight -4.1 kg (95% CI -5.9 to -2.4); HbA1c -0.18% (95% CI -0.29 to -0.07)",
        "sample_size": 796, "population": "Adults with overweight or type 2 diabetes",
        "dose_response": None,
        "causation_note": None,
        "tags": "vegan_diet,plant_based,cardiometabolic,weight_loss,cholesterol,diabetes",
        "url": "https://pubmed.ncbi.nlm.nih.gov/35672940/",
        "journal_tier": "q1", "domain": "nutrition",
    },
    {
        "pmid": "27301975", "doi": "10.1136/bmj.i2716",
        "title": "Whole grain consumption and risk of cardiovascular disease, cancer, and all cause and cause specific mortality",
        "authors": "Aune D et al.", "journal": "BMJ", "year": 2016,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 1,
        "summary": "Comprehensive dose-response meta-analysis showing whole grain intake is associated with significantly lower risk of CVD, cancer, and all-cause mortality.",
        "key_finding": "Each 90 g/day increase in whole grains was associated with 22% lower CVD risk and 17% lower all-cause mortality.",
        "effect_size": "RR 0.78 (95% CI 0.73-0.85) CVD; RR 0.83 (95% CI 0.77-0.90) all-cause mortality per 90 g/day",
        "sample_size": None, "population": "General adult population (45 prospective studies)",
        "dose_response": "Benefits observed up to 210-225 g/day (approximately 7 servings), with 3 servings/day (90g) showing substantial risk reduction.",
        "causation_note": "Observational data; strong dose-response relationship supports but does not prove causation.",
        "tags": "whole_grains,cardiovascular,cancer,mortality,dose_response",
        "url": "https://pubmed.ncbi.nlm.nih.gov/27301975/",
        "journal_tier": "elite", "domain": "nutrition",
    },
    {
        "pmid": "30638909", "doi": "10.1016/S0140-6736(18)31809-9",
        "title": "Carbohydrate quality and human health: a series of systematic reviews and meta-analyses",
        "authors": "Reynolds A et al.", "journal": "Lancet", "year": 2019,
        "study_type": "systematic_review", "evidence_grade": "A", "pillar_id": 1,
        "summary": "WHO-commissioned systematic review establishing optimal dietary fiber intake of 25-29 g/day for reducing mortality and chronic disease.",
        "key_finding": "Higher fiber intake (25-29 g/day) was associated with 15-30% decrease in all-cause and cardiovascular mortality.",
        "effect_size": "15-30% reduction in mortality; optimal intake 25-29 g/day",
        "sample_size": None, "population": "135 million person-years (185 prospective studies, 58 clinical trials)",
        "dose_response": "Each additional 8g/day of fiber reduces risk of CHD, type 2 diabetes, and colorectal cancer by 5-27%.",
        "causation_note": None,
        "tags": "dietary_fiber,whole_grains,cardiovascular,diabetes,cancer,WHO",
        "url": "https://pubmed.ncbi.nlm.nih.gov/30638909/",
        "journal_tier": "elite", "domain": "nutrition",
    },
    {
        "pmid": "38363072", "doi": "10.1080/10408398.2024.2317877",
        "title": "Ultra-processed food consumption and human health: an umbrella review of systematic reviews with meta-analyses",
        "authors": "Barbaresko J et al.", "journal": "Crit Rev Food Sci Nutr", "year": 2024,
        "study_type": "systematic_review", "evidence_grade": "A", "pillar_id": 1,
        "summary": "Umbrella review of 16 meta-analyses showing ultra-processed food consumption is associated with increased all-cause mortality, CVD, type 2 diabetes, and cancer.",
        "key_finding": "Ultra-processed food consumption associated with increased all-cause mortality, CVD, T2D, and colorectal cancer.",
        "effect_size": "Per 50 g/day: all-cause mortality RR 1.02; CVD RR 1.04; T2D per 10%: RR 1.12",
        "sample_size": None, "population": "General population (16 meta-analyses)",
        "dose_response": "Each 10% increase in ultra-processed food energy intake associated with 12% higher T2D risk.",
        "causation_note": "Observational evidence with GRADE moderate certainty; residual confounding possible.",
        "tags": "ultra_processed_food,mortality,cardiovascular,diabetes,cancer",
        "url": "https://pubmed.ncbi.nlm.nih.gov/38363072/",
        "journal_tier": "q1", "domain": "nutrition",
    },
    {
        "pmid": "28338764", "doi": "10.1093/ije/dyw319",
        "title": "Fruit and vegetable intake and the risk of cardiovascular disease, total cancer and all-cause mortality",
        "authors": "Aune D et al.", "journal": "Int J Epidemiol", "year": 2017,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 1,
        "summary": "Large meta-analysis establishing dose-response relationship between fruit/vegetable intake and major health outcomes.",
        "key_finding": "Each 200 g/day increase associated with 8% lower CVD risk, 3% lower cancer risk, and 10% lower all-cause mortality.",
        "effect_size": "RR 0.92 (95% CI 0.90-0.95) CVD; RR 0.90 (95% CI 0.87-0.93) all-cause mortality per 200 g/day",
        "sample_size": None, "population": "~2 million participants (95 studies)",
        "dose_response": "Risk reduction continues up to 800 g/day; estimated 7.8 million premature deaths attributable to intake below 800 g/day.",
        "causation_note": "Observational data; consistent dose-response across diverse populations strengthens evidence.",
        "tags": "fruit,vegetables,cardiovascular,cancer,mortality,dose_response",
        "url": "https://pubmed.ncbi.nlm.nih.gov/28338764/",
        "journal_tier": "q1", "domain": "nutrition",
    },
    {
        "pmid": "33641343", "doi": "10.1161/CIRCULATIONAHA.120.048996",
        "title": "Fruit and Vegetable Intake and Mortality: Results From 2 Prospective Cohort Studies and a Meta-Analysis of 26 Cohort Studies",
        "authors": "Wang DD et al.", "journal": "Circulation", "year": 2021,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 1,
        "summary": "Established the '5-a-day' threshold: approximately 5 servings/day (2 fruit + 3 vegetables) associated with lowest mortality risk.",
        "key_finding": "5 servings/day of fruits and vegetables was associated with lowest mortality; no additional benefit above 5 servings.",
        "effect_size": "HR 0.87 (95% CI 0.85-0.90) total mortality at 5 vs 2 servings/day",
        "sample_size": None, "population": "108,735 (cohorts) + 1,892,885 (meta-analysis); 145,015 deaths",
        "dose_response": "Optimal at 5 servings/day; plateau above this level.",
        "causation_note": "Observational; strong consistency across 26 international cohorts.",
        "tags": "fruit,vegetables,mortality,dose_response,five_a_day",
        "url": "https://pubmed.ncbi.nlm.nih.gov/33641343/",
        "journal_tier": "elite", "domain": "nutrition",
    },
    {
        "pmid": "28424256", "doi": "10.3945/jn.116.242552",
        "title": "Dietary Patterns and Type 2 Diabetes: A Systematic Literature Review and Meta-Analysis of Prospective Studies",
        "authors": "Jannasch F et al.", "journal": "J Nutr", "year": 2017,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 1,
        "summary": "Meta-analysis showing Mediterranean, DASH, and AHEI dietary patterns all significantly reduce type 2 diabetes risk.",
        "key_finding": "AHEI dietary pattern showed strongest risk reduction (21%), followed by DASH (19%) and Mediterranean (13%).",
        "effect_size": "Mediterranean RR 0.87; DASH RR 0.81; AHEI RR 0.79",
        "sample_size": None, "population": "48 articles, 16 prospective cohorts",
        "dose_response": None,
        "causation_note": "Observational evidence; multiple dietary patterns converge on similar protective effects.",
        "tags": "dietary_patterns,diabetes_prevention,mediterranean,DASH,AHEI",
        "url": "https://pubmed.ncbi.nlm.nih.gov/28424256/",
        "journal_tier": "q1", "domain": "nutrition",
    },
    {
        "pmid": "32114706", "doi": "10.1002/14651858.CD003177.pub5",
        "title": "Omega-3 fatty acids for the primary and secondary prevention of cardiovascular disease",
        "authors": "Abdelhamid AS et al.", "journal": "Cochrane Database Syst Rev", "year": 2020,
        "study_type": "systematic_review", "evidence_grade": "A", "pillar_id": 1,
        "summary": "Cochrane review of 86 RCTs showing omega-3 slightly reduces CHD mortality and events but has little effect on all-cause mortality or stroke.",
        "key_finding": "Omega-3 slightly reduces CHD mortality (RR 0.90) and CHD events (RR 0.91), reduces triglycerides by ~15%.",
        "effect_size": "CHD mortality RR 0.90 (95% CI 0.81-1.00); CHD events RR 0.91 (95% CI 0.85-0.97)",
        "sample_size": 162796, "population": "Adults with and without cardiovascular disease (86 RCTs)",
        "dose_response": None,
        "causation_note": None,
        "tags": "omega_3,fish_oil,cardiovascular,triglycerides,cochrane",
        "url": "https://pubmed.ncbi.nlm.nih.gov/32114706/",
        "journal_tier": "elite", "domain": "nutrition",
    },
    {
        "pmid": "23558162", "doi": "10.1136/bmj.f1325",
        "title": "Effect of longer term modest salt reduction on blood pressure: Cochrane systematic review and meta-analysis of randomised trials",
        "authors": "He FJ et al.", "journal": "BMJ", "year": 2013,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 1,
        "summary": "Cochrane review establishing that modest salt reduction significantly lowers blood pressure in both hypertensive and normotensive individuals.",
        "key_finding": "Modest salt reduction (~4.4 g/day) reduced SBP by 4.18 mmHg and DBP by 2.06 mmHg overall.",
        "effect_size": "SBP -4.18 mmHg (95% CI -5.18 to -3.18); DBP -2.06 mmHg (95% CI -2.67 to -1.45)",
        "sample_size": 3230, "population": "Hypertensive and normotensive adults (34 RCTs)",
        "dose_response": "Larger effects in hypertensives: SBP -5.39 mmHg vs normotensives: -2.42 mmHg.",
        "causation_note": None,
        "tags": "sodium,salt,blood_pressure,hypertension",
        "url": "https://pubmed.ncbi.nlm.nih.gov/23558162/",
        "journal_tier": "elite", "domain": "cardio_metabolic",
    },
    {
        "pmid": "28954418", "doi": "10.3390/nu9101063",
        "title": "Adherence to Mediterranean Diet and Risk of Cancer: An Updated Systematic Review and Meta-Analysis",
        "authors": "Schwingshackl L et al.", "journal": "Nutrients", "year": 2017,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 1,
        "summary": "Meta-analysis of 83 studies showing Mediterranean diet adherence is associated with significantly lower risk of multiple cancer types.",
        "key_finding": "Highest Mediterranean diet adherence associated with 14% lower cancer mortality and 18% lower colorectal cancer risk.",
        "effect_size": "Cancer mortality RR 0.86; colorectal RR 0.82; breast RR 0.92; gastric RR 0.72",
        "sample_size": None, "population": "2,130,753 participants (83 studies)",
        "dose_response": None,
        "causation_note": "Observational evidence; consistent across cancer types strengthens association.",
        "tags": "mediterranean_diet,cancer,colorectal,breast_cancer",
        "url": "https://pubmed.ncbi.nlm.nih.gov/28954418/",
        "journal_tier": "q1", "domain": "nutrition",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # PILLAR 2: PHYSICAL ACTIVITY (pillar_id=2)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "pmid": "31434697", "doi": "10.1136/bmj.l4570",
        "title": "Dose-response associations between accelerometry measured physical activity and sedentary time and all cause mortality",
        "authors": "Ekelund U et al.", "journal": "BMJ", "year": 2019,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 2,
        "summary": "Harmonised meta-analysis using accelerometer data showing any physical activity at any intensity substantially lowers mortality risk.",
        "key_finding": "Most active quartile had 73% lower mortality; most sedentary quartile had 163% higher mortality vs least sedentary.",
        "effect_size": "Most active vs least active: HR 0.27 (95% CI 0.23-0.32)",
        "sample_size": 36383, "population": "Adults (8 studies with accelerometer data)",
        "dose_response": "Non-linear: greatest benefits at lowest activity levels; any movement counts.",
        "causation_note": "Observational with objective measurement (accelerometers); reduces self-report bias.",
        "tags": "physical_activity,mortality,accelerometer,dose_response,sedentary",
        "url": "https://pubmed.ncbi.nlm.nih.gov/31434697/",
        "journal_tier": "elite", "domain": "exercise_science",
    },
    {
        "pmid": "35247352", "doi": "10.1016/S2468-2667(21)00302-9",
        "title": "Daily steps and all-cause mortality: a meta-analysis of 15 international cohorts",
        "authors": "Paluch AE et al.", "journal": "Lancet Public Health", "year": 2022,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 2,
        "summary": "Meta-analysis establishing step count targets: benefits plateau at 6,000-8,000 steps/day for adults 60+ and 8,000-10,000 for adults under 60.",
        "key_finding": "Top quartile (~10,901 steps/day) had 53% lower mortality; age-specific plateaus identified.",
        "effect_size": "Q4 vs Q1: HR 0.47 (95% CI 0.39-0.57)",
        "sample_size": 47471, "population": "Adults from 15 international cohorts; 3,013 deaths",
        "dose_response": "Adults 60+: plateau at 6,000-8,000 steps/day. Adults <60: plateau at 8,000-10,000 steps/day.",
        "causation_note": "Observational; reverse causation possible (sicker people walk less).",
        "tags": "steps,walking,mortality,dose_response,age_specific",
        "url": "https://pubmed.ncbi.nlm.nih.gov/35247352/",
        "journal_tier": "elite", "domain": "exercise_science",
    },
    {
        "pmid": "37555441", "doi": "10.1093/eurjpc/zwad229",
        "title": "The association between daily step count and all-cause and cardiovascular mortality: a meta-analysis",
        "authors": "Banach M et al.", "journal": "Eur J Prev Cardiol", "year": 2023,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 2,
        "summary": "Meta-analysis showing benefits begin at very low step counts (2,337 steps/day for CV mortality) with each additional 1,000 steps reducing mortality by 15%.",
        "key_finding": "Each 1,000-step/day increment associated with 15% lower all-cause mortality; benefits start at ~2,337 steps/day for CV mortality.",
        "effect_size": "Per 1000 steps: HR 0.85 (95% CI 0.81-0.91); per 500 steps CV: HR 0.93 (95% CI 0.91-0.95)",
        "sample_size": 226889, "population": "17 cohort studies, general adult population",
        "dose_response": "Linear dose-response: every additional 1,000 steps provides incremental benefit.",
        "causation_note": "Observational; consistent dose-response across multiple cohorts.",
        "tags": "steps,walking,cardiovascular_mortality,dose_response",
        "url": "https://pubmed.ncbi.nlm.nih.gov/37555441/",
        "journal_tier": "q1", "domain": "exercise_science",
    },
    {
        "pmid": "35599175", "doi": "10.1016/j.amepre.2022.03.020",
        "title": "Resistance Training and Mortality Risk: A Systematic Review and Meta-Analysis",
        "authors": "Shailendra P et al.", "journal": "Am J Prev Med", "year": 2022,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 2,
        "summary": "First meta-analysis to quantify the dose-response relationship between resistance training and mortality.",
        "key_finding": "Any resistance training reduced all-cause mortality by 15%, CVD mortality by 19%, and cancer mortality by 14%.",
        "effect_size": "All-cause RR 0.85; CVD RR 0.81; cancer RR 0.86; optimal at 60 min/wk: RR 0.73",
        "sample_size": None, "population": "10 prospective studies, general adult population",
        "dose_response": "Maximum risk reduction of 27% at approximately 60 minutes/week; benefits diminish at higher volumes.",
        "causation_note": "Observational; J-shaped dose-response suggests optimal range.",
        "tags": "resistance_training,strength_training,mortality,dose_response",
        "url": "https://pubmed.ncbi.nlm.nih.gov/35599175/",
        "journal_tier": "q1", "domain": "exercise_science",
    },
    {
        "pmid": "26092138", "doi": "10.1007/s10654-015-0056-z",
        "title": "Physical activity and the risk of type 2 diabetes: a systematic review and dose-response meta-analysis",
        "authors": "Aune D et al.", "journal": "Eur J Epidemiol", "year": 2015,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 2,
        "summary": "Comprehensive meta-analysis showing all types of physical activity reduce type 2 diabetes risk, with steepest benefits at low activity levels.",
        "key_finding": "High vs low total physical activity associated with 35% lower T2D risk; even walking reduces risk by 15%.",
        "effect_size": "Total PA: RR 0.65; leisure-time: RR 0.74; walking: RR 0.85",
        "sample_size": None, "population": "81 prospective studies",
        "dose_response": "Non-linear: steepest risk reductions at lowest activity levels; any movement helps.",
        "causation_note": "Observational; supports but does not prove causation.",
        "tags": "physical_activity,diabetes_prevention,walking,dose_response",
        "url": "https://pubmed.ncbi.nlm.nih.gov/26092138/",
        "journal_tier": "q1", "domain": "exercise_science",
    },
    {
        "pmid": "38355154", "doi": "10.1136/bmj-2023-075847",
        "title": "Effect of exercise for depression: systematic review and network meta-analysis of randomised controlled trials",
        "authors": "Noetel M et al.", "journal": "BMJ", "year": 2024,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 2,
        "summary": "Largest network meta-analysis of exercise for depression (218 RCTs), identifying walking/jogging, yoga, and strength training as most effective.",
        "key_finding": "Walking/jogging showed the largest effect for depression (Hedges' g -0.62), followed by yoga (-0.55) and strength training (-0.49).",
        "effect_size": "Walking/jogging g -0.62; yoga g -0.55; strength training g -0.49",
        "sample_size": 14170, "population": "Adults with major depressive disorder (218 RCTs)",
        "dose_response": "Effects proportional to exercise intensity; higher intensity = larger benefit.",
        "causation_note": None,
        "tags": "exercise,depression,mental_health,walking,yoga,strength_training",
        "url": "https://pubmed.ncbi.nlm.nih.gov/38355154/",
        "journal_tier": "elite", "domain": "exercise_science",
    },
    {
        "pmid": "27475271", "doi": "10.1016/S0140-6736(16)30370-1",
        "title": "Does physical activity attenuate, or even eliminate, the detrimental association of sitting time with mortality?",
        "authors": "Ekelund U et al.", "journal": "Lancet", "year": 2016,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 2,
        "summary": "Landmark study showing 60-75 min/day of moderate exercise can eliminate the increased mortality risk from prolonged sitting.",
        "key_finding": "60-75 min/day of moderate exercise eliminated the mortality risk from sitting >8 hours/day.",
        "effect_size": "Sitting >8h + low PA: HR 1.59; sitting >8h + high PA: HR 1.04 (not significant)",
        "sample_size": 1005791, "population": "Over 1 million adults (16 studies); 84,609 deaths",
        "dose_response": "60-75 min/day of moderate activity fully attenuates sitting risk.",
        "causation_note": "Observational; interaction effect between sitting and activity levels.",
        "tags": "sedentary_behavior,sitting,mortality,physical_activity",
        "url": "https://pubmed.ncbi.nlm.nih.gov/27475271/",
        "journal_tier": "elite", "domain": "exercise_science",
    },
    {
        "pmid": "26243014", "doi": "10.1007/s40279-015-0365-0",
        "title": "Effectiveness of High-Intensity Interval Training (HIT) and Continuous Endurance Training for VO2max Improvements",
        "authors": "Milanovic Z et al.", "journal": "Sports Med", "year": 2015,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 2,
        "summary": "Meta-analysis comparing HIIT and continuous endurance training showing both improve VO2max, with HIIT having a small additional benefit.",
        "key_finding": "HIIT improved VO2max by 5.5 mL/kg/min vs control; small additional benefit of 1.2 mL/kg/min vs continuous training.",
        "effect_size": "HIIT vs control: +5.5 mL/kg/min; HIIT vs endurance: +1.2 mL/kg/min",
        "sample_size": 723, "population": "Adults (28 controlled trials)",
        "dose_response": None,
        "causation_note": None,
        "tags": "HIIT,high_intensity_interval_training,VO2max,cardiorespiratory_fitness",
        "url": "https://pubmed.ncbi.nlm.nih.gov/26243014/",
        "journal_tier": "q1", "domain": "exercise_science",
    },
    {
        "pmid": "34004389", "doi": "10.1016/j.jshs.2021.05.003",
        "title": "Comparative efficacy of various exercise interventions on cognitive function in patients with mild cognitive impairment or dementia",
        "authors": "Huang X et al.", "journal": "J Sport Health Sci", "year": 2022,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 2,
        "summary": "Network meta-analysis showing all exercise types effective for cognition in MCI/dementia, with resistance exercise most effective.",
        "key_finding": "Resistance exercise had the highest efficacy for global cognition (SMD 1.05) and executive function (SMD 0.85) in MCI/dementia.",
        "effect_size": "Resistance: SMD 1.05 (95% CI 0.56-1.54) global cognition",
        "sample_size": 5606, "population": "Adults with MCI or dementia (71 RCTs)",
        "dose_response": None,
        "causation_note": None,
        "tags": "exercise,cognitive_function,dementia,MCI,resistance_training",
        "url": "https://pubmed.ncbi.nlm.nih.gov/34004389/",
        "journal_tier": "q1", "domain": "exercise_science",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # PILLAR 3: SLEEP (pillar_id=3)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "pmid": "20469800", "doi": "10.1093/sleep/33.5.585",
        "title": "Sleep duration and all-cause mortality: a systematic review and meta-analysis of prospective studies",
        "authors": "Cappuccio FP et al.", "journal": "Sleep", "year": 2010,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 3,
        "summary": "Landmark meta-analysis establishing both short and long sleep as predictors of mortality.",
        "key_finding": "Short sleep associated with 12% greater mortality risk; long sleep with 30% greater risk.",
        "effect_size": "Short: RR 1.12 (95% CI 1.06-1.18); Long: RR 1.30 (95% CI 1.22-1.38)",
        "sample_size": 1382999, "population": "16 studies, 27 cohorts, 112,566 deaths",
        "dose_response": "U-shaped: optimal at 7-8 hours; both extremes increase risk.",
        "causation_note": "Observational; long sleep may indicate underlying illness (reverse causation).",
        "tags": "sleep,mortality,sleep_duration",
        "url": "https://pubmed.ncbi.nlm.nih.gov/20469800/",
        "journal_tier": "q1", "domain": "sleep_science",
    },
    {
        "pmid": "28889101", "doi": "10.1161/JAHA.117.005947",
        "title": "Relationship of Sleep Duration With All-Cause Mortality and Cardiovascular Events",
        "authors": "Yin J et al.", "journal": "J Am Heart Assoc", "year": 2017,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 3,
        "summary": "Dose-response meta-analysis showing U-shaped relationship between sleep duration and mortality/CVD, with lowest risk at ~7 hours.",
        "key_finding": "Each 1-hour reduction below 7h increased mortality by 6%; each 1-hour increase above 7h by 13%.",
        "effect_size": "<7h: RR 1.06 per 1h reduction; >7h: RR 1.13 per 1h increment",
        "sample_size": None, "population": "Prospective cohort studies",
        "dose_response": "Optimal at 7 hours; risk increases symmetrically in both directions.",
        "causation_note": "Observational; strong dose-response pattern.",
        "tags": "sleep,mortality,cardiovascular,dose_response",
        "url": "https://pubmed.ncbi.nlm.nih.gov/28889101/",
        "journal_tier": "q1", "domain": "sleep_science",
    },
    {
        "pmid": "26140821", "doi": "10.1016/j.biopsych.2015.05.014",
        "title": "Sleep Disturbance, Sleep Duration, and Inflammation: A Systematic Review and Meta-Analysis",
        "authors": "Irwin MR et al.", "journal": "Biol Psychiatry", "year": 2016,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 3,
        "summary": "Meta-analysis demonstrating that poor sleep drives systemic inflammation independent of sleep duration.",
        "key_finding": "Sleep disturbance associated with higher CRP (ES 0.12) and IL-6 (ES 0.20), driving systemic inflammation.",
        "effect_size": "CRP ES 0.12 (95% CI 0.05-0.19); IL-6 ES 0.20 (95% CI 0.08-0.31)",
        "sample_size": None, "population": ">50,000 participants (72 studies)",
        "dose_response": None,
        "causation_note": "Mixed evidence; experimental sleep deprivation studies support causal pathway.",
        "tags": "sleep,inflammation,immune_function,CRP,IL6",
        "url": "https://pubmed.ncbi.nlm.nih.gov/26140821/",
        "journal_tier": "elite", "domain": "sleep_science",
    },
    {
        "pmid": "33054339", "doi": "10.1139/apnm-2020-0032",
        "title": "Sleep timing, sleep consistency, and health in adults: a systematic review",
        "authors": "Chaput JP et al.", "journal": "Appl Physiol Nutr Metab", "year": 2020,
        "study_type": "systematic_review", "evidence_grade": "A", "pillar_id": 3,
        "summary": "Systematic review establishing that regular sleep patterns (consistent bedtimes/wake times) are associated with better health outcomes.",
        "key_finding": "Later sleep timing and greater variability in sleep patterns were associated with adverse health outcomes across multiple domains.",
        "effect_size": None,
        "sample_size": None, "population": "92,340 participants (41 studies)",
        "dose_response": None,
        "causation_note": "Observational; regularity may be a marker of overall health behaviors.",
        "tags": "sleep,circadian_rhythm,sleep_hygiene,consistency",
        "url": "https://pubmed.ncbi.nlm.nih.gov/33054339/",
        "journal_tier": "q2", "domain": "sleep_science",
    },
    {
        "pmid": "27743803", "doi": "10.1016/j.sleep.2016.08.006",
        "title": "Short sleep duration and health outcomes: a systematic review, meta-analysis, and meta-regression",
        "authors": "Itani O et al.", "journal": "Sleep Med", "year": 2017,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 3,
        "summary": "Comprehensive meta-analysis linking short sleep to multiple chronic disease outcomes.",
        "key_finding": "Short sleep significantly associated with diabetes (RR 1.37), obesity (RR 1.38), CVD (RR 1.16), and mortality (RR 1.12).",
        "effect_size": "Diabetes RR 1.37; Obesity RR 1.38; CVD RR 1.16; CHD RR 1.26",
        "sample_size": 5172710, "population": "153 studies, general adult population",
        "dose_response": None,
        "causation_note": "Observational with consistent results across outcomes and populations.",
        "tags": "sleep,cardiovascular,diabetes,obesity,mortality",
        "url": "https://pubmed.ncbi.nlm.nih.gov/27743803/",
        "journal_tier": "q1", "domain": "sleep_science",
    },
    {
        "pmid": "25715415", "doi": "10.2337/dc14-2073",
        "title": "Sleep duration and risk of type 2 diabetes: a meta-analysis of prospective studies",
        "authors": "Shan Z et al.", "journal": "Diabetes Care", "year": 2015,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 3,
        "summary": "Meta-analysis showing U-shaped relationship between sleep duration and type 2 diabetes risk.",
        "key_finding": "Each 1h shorter sleep below 7h increased T2D risk by 9%; each 1h longer above 8h by 14%.",
        "effect_size": "<7h: RR 1.09 per 1h; >8h: RR 1.14 per 1h",
        "sample_size": 482502, "population": "10 articles, 18,443 incident T2D cases",
        "dose_response": "Optimal at 7-8 hours; risk increases in both directions.",
        "causation_note": "Observational; experimental evidence supports metabolic mechanisms.",
        "tags": "sleep,diabetes,metabolic_health,dose_response",
        "url": "https://pubmed.ncbi.nlm.nih.gov/25715415/",
        "journal_tier": "elite", "domain": "sleep_science",
    },
    {
        "pmid": "23691095", "doi": "10.1371/journal.pone.0063773",
        "title": "Meta-analysis: melatonin for the treatment of primary sleep disorders",
        "authors": "Ferracioli-Oda E et al.", "journal": "PLoS One", "year": 2013,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 3,
        "summary": "Meta-analysis of 19 RCTs showing melatonin significantly improves sleep onset, duration, and quality.",
        "key_finding": "Melatonin reduced sleep onset latency by 7 minutes, increased sleep time by 8 minutes, and improved sleep quality.",
        "effect_size": "Latency WMD -7.06 min; Sleep quality SMD 0.22 (95% CI 0.12-0.32)",
        "sample_size": 1683, "population": "Adults with primary sleep disorders (19 RCTs)",
        "dose_response": "Effects do not dissipate with continued use.",
        "causation_note": None,
        "tags": "sleep,melatonin,supplementation,insomnia",
        "url": "https://pubmed.ncbi.nlm.nih.gov/23691095/",
        "journal_tier": "q2", "domain": "sleep_science",
    },
    {
        "pmid": "27804960", "doi": "10.1038/ejcn.2016.201",
        "title": "The effects of partial sleep deprivation on energy balance: a systematic review and meta-analysis",
        "authors": "Al Khatib HK et al.", "journal": "Eur J Clin Nutr", "year": 2017,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 3,
        "summary": "Meta-analysis showing sleep deprivation significantly increases caloric intake without changing expenditure, promoting weight gain.",
        "key_finding": "Partial sleep deprivation increased energy intake by 385 kcal/day with no change in expenditure.",
        "effect_size": "+385 kcal/day (95% CI 252-517, p<0.00001)",
        "sample_size": 496, "population": "17 studies; healthy adults",
        "dose_response": None,
        "causation_note": "Experimental evidence supports causal mechanism (controlled sleep restriction).",
        "tags": "sleep,obesity,weight_gain,energy_balance,appetite",
        "url": "https://pubmed.ncbi.nlm.nih.gov/27804960/",
        "journal_tier": "q1", "domain": "sleep_science",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # PILLAR 4: STRESS MANAGEMENT (pillar_id=4)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "pmid": "25818837", "doi": "10.1016/j.jpsychores.2015.03.009",
        "title": "Mindfulness-based stress reduction for healthy individuals: A meta-analysis",
        "authors": "Khoury B et al.", "journal": "J Psychosom Res", "year": 2015,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 4,
        "summary": "Meta-analysis showing MBSR is moderately effective for reducing stress, anxiety, and depression in healthy individuals.",
        "key_finding": "MBSR showed moderate effect size (Hedges' g=0.53) for healthy individuals, with large effects on stress.",
        "effect_size": "Between-group Hedges' g=0.53 (95% CI 0.41-0.64)",
        "sample_size": 2668, "population": "Healthy individuals (29 studies)",
        "dose_response": "Effects maintained at 19-week follow-up.",
        "causation_note": None,
        "tags": "stress,mindfulness,MBSR,anxiety,depression",
        "url": "https://pubmed.ncbi.nlm.nih.gov/25818837/",
        "journal_tier": "q1", "domain": "stress_pni",
    },
    {
        "pmid": "24395196", "doi": "10.1001/jamainternmed.2013.13018",
        "title": "Meditation programs for psychological stress and well-being: a systematic review and meta-analysis",
        "authors": "Goyal M et al.", "journal": "JAMA Intern Med", "year": 2014,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 4,
        "summary": "Landmark JAMA review of 47 RCTs showing moderate evidence for meditation improving anxiety, depression, and pain.",
        "key_finding": "Mindfulness meditation showed moderate improvements in anxiety (ES 0.38), depression (ES 0.30), and pain (ES 0.33).",
        "effect_size": "Anxiety ES 0.38; Depression ES 0.30; Pain ES 0.33",
        "sample_size": 3515, "population": "Adults with various conditions (47 RCTs)",
        "dose_response": "Effects observed at 8 weeks and maintained at 3-6 months.",
        "causation_note": None,
        "tags": "stress,meditation,anxiety,depression,pain,JAMA",
        "url": "https://pubmed.ncbi.nlm.nih.gov/24395196/",
        "journal_tier": "elite", "domain": "stress_pni",
    },
    {
        "pmid": "29697885", "doi": "10.1002/da.22762",
        "title": "Yoga for anxiety: A systematic review and meta-analysis of randomized controlled trials",
        "authors": "Cramer H et al.", "journal": "Depress Anxiety", "year": 2018,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 4,
        "summary": "Meta-analysis showing yoga has small but significant effects on anxiety compared to no treatment.",
        "key_finding": "Yoga showed significant anxiety reduction vs no treatment (SMD -0.43) and vs active comparators (SMD -0.86).",
        "effect_size": "vs no treatment SMD -0.43; vs active comparators SMD -0.86",
        "sample_size": 319, "population": "Adults with anxiety (8 RCTs)",
        "dose_response": None,
        "causation_note": None,
        "tags": "stress,yoga,anxiety,mental_health",
        "url": "https://pubmed.ncbi.nlm.nih.gov/29697885/",
        "journal_tier": "q1", "domain": "stress_pni",
    },
    {
        "pmid": "35623448", "doi": "10.1016/j.neubiorev.2022.104711",
        "title": "Effects of voluntary slow breathing on heart rate and heart rate variability",
        "authors": "Laborde S et al.", "journal": "Neurosci Biobehav Rev", "year": 2022,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 4,
        "summary": "Large-scale meta-analysis confirming slow breathing activates parasympathetic nervous system via increased vagal-mediated HRV.",
        "key_finding": "Voluntary slow breathing significantly increased vagally-mediated HRV during practice and after multi-session interventions.",
        "effect_size": "Significant increases in vmHRV across all timepoints (223 studies)",
        "sample_size": None, "population": "223 studies from 1,842 abstracts screened",
        "dose_response": "Effects present during single sessions and accumulate with regular practice.",
        "causation_note": None,
        "tags": "stress,breathing,HRV,autonomic,parasympathetic",
        "url": "https://pubmed.ncbi.nlm.nih.gov/35623448/",
        "journal_tier": "elite", "domain": "stress_pni",
    },
    {
        "pmid": "34646931", "doi": "10.1016/j.ssmph.2021.100934",
        "title": "Nature-based outdoor activities for mental and physical health",
        "authors": "Coventry PA et al.", "journal": "SSM Popul Health", "year": 2021,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 4,
        "summary": "Meta-analysis showing nature-based interventions significantly reduce depression and anxiety while improving positive affect.",
        "key_finding": "Nature interventions improved depression (ES -0.64), anxiety (ES -0.94), and positive affect (ES 0.95).",
        "effect_size": "Depression -0.64; Anxiety -0.94; Positive affect 0.95",
        "sample_size": None, "population": "50 studies (16 RCTs, 18 controlled, 16 uncontrolled)",
        "dose_response": "Optimal dose: 20-90 minute sessions over 8-12 weeks.",
        "causation_note": "RCT subset supports causal effects; observational studies show larger effects.",
        "tags": "stress,nature,green_space,mental_health,depression,anxiety",
        "url": "https://pubmed.ncbi.nlm.nih.gov/34646931/",
        "journal_tier": "q2", "domain": "stress_pni",
    },
    {
        "pmid": "28415916", "doi": "10.1080/01616412.2017.1317904",
        "title": "Association between psychosocial stress and hypertension: a systematic review and meta-analysis",
        "authors": "Liu MY et al.", "journal": "Neurol Res", "year": 2017,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 4,
        "summary": "Meta-analysis establishing the link between chronic psychosocial stress and hypertension risk.",
        "key_finding": "Psychosocial stress associated with 2.4-fold increased risk of hypertension.",
        "effect_size": "OR 2.40 (95% CI 1.65-3.49)",
        "sample_size": 5696, "population": "11 studies, general population",
        "dose_response": None,
        "causation_note": "Observational; plausible biological mechanism via HPA axis and sympathetic activation.",
        "tags": "stress,cardiovascular,hypertension,chronic_stress",
        "url": "https://pubmed.ncbi.nlm.nih.gov/28415916/",
        "journal_tier": "q3", "domain": "stress_pni",
    },
    {
        "pmid": "37585888", "doi": "10.31744/einstein_journal/2023RW0371",
        "title": "The effects of gratitude interventions: a systematic review and meta-analysis",
        "authors": "Diniz G et al.", "journal": "Einstein (Sao Paulo)", "year": 2023,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 4,
        "summary": "Meta-analysis of 64 RCTs showing gratitude interventions improve mental health and reduce anxiety and depression.",
        "key_finding": "Gratitude interventions significantly increased positive mood and reduced anxiety and depression symptoms.",
        "effect_size": None,
        "sample_size": None, "population": "64 RCTs",
        "dose_response": None,
        "causation_note": None,
        "tags": "stress,gratitude,well_being,positive_psychology,anxiety,depression",
        "url": "https://pubmed.ncbi.nlm.nih.gov/37585888/",
        "journal_tier": "q3", "domain": "stress_pni",
    },
    {
        "pmid": "15250815", "doi": "10.1037/0033-2909.130.4.601",
        "title": "Psychological stress and the human immune system: a meta-analytic study of 30 years of inquiry",
        "authors": "Segerstrom SC et al.", "journal": "Psychol Bull", "year": 2004,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 4,
        "summary": "Landmark 30-year meta-analysis establishing the psychoneuroimmunology stress-immune pathway.",
        "key_finding": "Acute stressors upregulate natural immunity but chronic stressors suppress both cellular and humoral immunity.",
        "effect_size": None,
        "sample_size": None, "population": "300+ empirical studies over 30 years",
        "dose_response": "Chronic stress has cumulative immunosuppressive effects; older adults more vulnerable.",
        "causation_note": "Both experimental and observational evidence support causal mechanisms.",
        "tags": "stress,immune_function,psychoneuroimmunology,chronic_stress",
        "url": "https://pubmed.ncbi.nlm.nih.gov/15250815/",
        "journal_tier": "elite", "domain": "stress_pni",
    },
    {
        "pmid": "28478782", "doi": "10.1017/S0033291717001003",
        "title": "The effect of heart rate variability biofeedback training on stress and anxiety: a meta-analysis",
        "authors": "Goessl VC et al.", "journal": "Psychol Med", "year": 2017,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 4,
        "summary": "Meta-analysis showing HRV biofeedback produces large reductions in stress and anxiety.",
        "key_finding": "HRV biofeedback training showed large effect sizes for stress/anxiety reduction (Hedges' g=0.81-0.83).",
        "effect_size": "Within-group Hedges' g=0.81; Between-groups g=0.83",
        "sample_size": 484, "population": "24 studies, adults with and without anxiety disorders",
        "dose_response": "Effects not moderated by number of sessions.",
        "causation_note": None,
        "tags": "stress,HRV,biofeedback,anxiety,wearable",
        "url": "https://pubmed.ncbi.nlm.nih.gov/28478782/",
        "journal_tier": "q1", "domain": "stress_pni",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # PILLAR 5: SOCIAL CONNECTION (pillar_id=5)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "pmid": "20668659", "doi": "10.1371/journal.pmed.1000316",
        "title": "Social relationships and mortality risk: a meta-analytic review",
        "authors": "Holt-Lunstad J et al.", "journal": "PLoS Med", "year": 2010,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 5,
        "summary": "Landmark meta-analysis establishing social relationships as a major mortality risk factor, comparable to smoking cessation.",
        "key_finding": "Stronger social relationships associated with 50% increased likelihood of survival.",
        "effect_size": "OR 1.50 (95% CI 1.42-1.59); complex integration: OR 1.91 (95% CI 1.63-2.23)",
        "sample_size": 308849, "population": "148 prospective studies",
        "dose_response": None,
        "causation_note": "Observational; effect magnitude comparable to quitting smoking or physical activity.",
        "tags": "social_connection,mortality,social_integration,landmark",
        "url": "https://pubmed.ncbi.nlm.nih.gov/20668659/",
        "journal_tier": "elite", "domain": "longevity",
    },
    {
        "pmid": "25910392", "doi": "10.1177/1745691614568352",
        "title": "Loneliness and social isolation as risk factors for mortality: a meta-analytic review",
        "authors": "Holt-Lunstad J et al.", "journal": "Perspect Psychol Sci", "year": 2015,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 5,
        "summary": "Follow-up meta-analysis showing social isolation, loneliness, and living alone each independently increase mortality risk.",
        "key_finding": "Social isolation (OR 1.29), loneliness (OR 1.26), and living alone (OR 1.32) each significantly increase mortality risk.",
        "effect_size": "Social isolation OR 1.29; Loneliness OR 1.26; Living alone OR 1.32",
        "sample_size": 3407134, "population": "70 studies, general population",
        "dose_response": None,
        "causation_note": "Observational; effects persist after controlling for demographics and health status.",
        "tags": "social_connection,loneliness,social_isolation,mortality,landmark",
        "url": "https://pubmed.ncbi.nlm.nih.gov/25910392/",
        "journal_tier": "q1", "domain": "longevity",
    },
    {
        "pmid": "37337095", "doi": "10.1038/s41562-023-01617-6",
        "title": "A systematic review and meta-analysis of 90 cohort studies of social isolation, loneliness and mortality",
        "authors": "Wang F et al.", "journal": "Nat Hum Behav", "year": 2023,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 5,
        "summary": "Largest meta-analysis to date confirming social isolation increases mortality across all major causes of death.",
        "key_finding": "Social isolation associated with 32% increased all-cause mortality, 34% CVD mortality, 24% cancer mortality.",
        "effect_size": "All-cause ES 1.32 (95% CI 1.26-1.39); CVD ES 1.34 (95% CI 1.25-1.44)",
        "sample_size": 2205199, "population": "90 cohort studies",
        "dose_response": None,
        "causation_note": "Observational; effect persists across multiple causes of death.",
        "tags": "social_connection,social_isolation,loneliness,mortality,cardiovascular,cancer",
        "url": "https://pubmed.ncbi.nlm.nih.gov/37337095/",
        "journal_tier": "elite", "domain": "longevity",
    },
    {
        "pmid": "27091846", "doi": "10.1136/heartjnl-2015-308790",
        "title": "Loneliness and social isolation as risk factors for coronary heart disease and stroke",
        "authors": "Valtorta NK et al.", "journal": "Heart", "year": 2016,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 5,
        "summary": "Meta-analysis showing poor social relationships increase risk of both CHD and stroke.",
        "key_finding": "Poor social relationships associated with 29% increase in CHD and 32% increase in stroke risk.",
        "effect_size": "CHD: RR 1.29 (95% CI 1.04-1.59); Stroke: RR 1.32 (95% CI 1.04-1.68)",
        "sample_size": None, "population": "16 longitudinal datasets, 7,630 events",
        "dose_response": None,
        "causation_note": "Observational; plausible mechanisms via stress, inflammation, and health behaviors.",
        "tags": "social_connection,cardiovascular,coronary_heart_disease,stroke,loneliness",
        "url": "https://pubmed.ncbi.nlm.nih.gov/27091846/",
        "journal_tier": "q1", "domain": "cardio_metabolic",
    },
    {
        "pmid": "30452410", "doi": "10.3233/JAD-180439",
        "title": "The Association between Social Engagement, Loneliness, and Risk of Dementia",
        "authors": "Penninkilampi R et al.", "journal": "J Alzheimers Dis", "year": 2018,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 5,
        "summary": "Meta-analysis showing poor social networks significantly increase dementia risk.",
        "key_finding": "Poor social network associated with 59% increased dementia risk; good social engagement modestly protective (RR 0.88).",
        "effect_size": "Poor network: RR 1.59 (95% CI 1.31-1.96); Protective: RR 0.88 (95% CI 0.80-0.96)",
        "sample_size": 2370452, "population": "33 studies",
        "dose_response": None,
        "causation_note": "Observational; cognitive stimulation and stress buffering proposed as mechanisms.",
        "tags": "social_connection,dementia,cognitive_decline,social_engagement",
        "url": "https://pubmed.ncbi.nlm.nih.gov/30452410/",
        "journal_tier": "q1", "domain": "gerontology",
    },
    {
        "pmid": "23421326", "doi": "10.1037/a0031519",
        "title": "Volunteering by older adults and risk of mortality: a meta-analysis",
        "authors": "Okun MA et al.", "journal": "Psychol Aging", "year": 2013,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 5,
        "summary": "Meta-analysis showing volunteering reduces mortality risk by 24% in older adults.",
        "key_finding": "Volunteering reduced mortality risk by 24% after adjusting for confounders.",
        "effect_size": "Adjusted RR 0.76 (95% CI 0.69-0.84)",
        "sample_size": None, "population": "Older adults 55+, multiple studies",
        "dose_response": None,
        "causation_note": "Observational; healthy volunteer effect may partially explain results.",
        "tags": "social_connection,volunteering,mortality,older_adults",
        "url": "https://pubmed.ncbi.nlm.nih.gov/23421326/",
        "journal_tier": "q1", "domain": "gerontology",
    },
    {
        "pmid": "17011690", "doi": "10.1016/j.socscimed.2006.08.031",
        "title": "Marital status and mortality in the elderly: a systematic review and meta-analysis",
        "authors": "Manzoli L et al.", "journal": "Soc Sci Med", "year": 2007,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 5,
        "summary": "Meta-analysis showing marriage is associated with 12% lower mortality risk in elderly populations.",
        "key_finding": "Being married associated with 12% lower mortality risk compared to non-married individuals.",
        "effect_size": "Married vs non-married: RR 0.88 (95% CI 0.85-0.91)",
        "sample_size": None, "population": "250,000+ elderly (53 comparisons)",
        "dose_response": None,
        "causation_note": "Observational; selection bias (healthier people more likely to marry) may contribute.",
        "tags": "social_connection,marriage,mortality,older_adults",
        "url": "https://pubmed.ncbi.nlm.nih.gov/17011690/",
        "journal_tier": "q1", "domain": "gerontology",
    },
    {
        "pmid": "17652652", "doi": "10.1056/NEJMsa066082",
        "title": "The spread of obesity in a large social network over 32 years",
        "authors": "Christakis NA, Fowler JH", "journal": "N Engl J Med", "year": 2007,
        "study_type": "cohort", "evidence_grade": "C", "pillar_id": 5,
        "summary": "Landmark Framingham study showing health behaviors spread through social networks.",
        "key_finding": "A person's chances of becoming obese increased by 57% if a friend became obese; 40% for siblings, 37% for spouses.",
        "effect_size": "57% increased obesity risk (95% CI 6%-123%) from friend obesity",
        "sample_size": 12067, "population": "Framingham Heart Study, 32 years follow-up",
        "dose_response": None,
        "causation_note": "Observational; demonstrates social contagion of health behaviors, not biological causation.",
        "tags": "social_connection,social_networks,obesity,health_behaviors,landmark",
        "url": "https://pubmed.ncbi.nlm.nih.gov/17652652/",
        "journal_tier": "elite", "domain": "lifestyle_medicine",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # PILLAR 6: SUBSTANCE AVOIDANCE (pillar_id=6)
    # ═══════════════════════════════════════════════════════════════════════
    {
        "pmid": "30146330", "doi": "10.1016/S0140-6736(18)31310-2",
        "title": "Alcohol use and burden for 195 countries and territories, 1990-2016: Global Burden of Disease Study 2016",
        "authors": "GBD 2016 Alcohol Collaborators", "journal": "Lancet", "year": 2018,
        "study_type": "systematic_review", "evidence_grade": "A", "pillar_id": 6,
        "summary": "Landmark Global Burden of Disease analysis establishing no safe level of alcohol consumption.",
        "key_finding": "The level of alcohol consumption that minimized health loss was zero standard drinks per week.",
        "effect_size": "Minimizing dose = 0 (95% UI 0.0-0.8) standard drinks/week",
        "sample_size": None, "population": "195 countries; 694 data sources + 592 studies",
        "dose_response": "Any alcohol consumption increases net health risk; no protective threshold identified.",
        "causation_note": "Comprehensive multi-country analysis; reverses prior claims of J-shaped curve.",
        "tags": "substance_avoidance,alcohol,mortality,no_safe_level,landmark",
        "url": "https://pubmed.ncbi.nlm.nih.gov/30146330/",
        "journal_tier": "elite", "domain": "toxicology",
    },
    {
        "pmid": "35333364", "doi": "10.1001/jamanetworkopen.2022.3849",
        "title": "Association of Habitual Alcohol Intake With Risk of Cardiovascular Disease",
        "authors": "Biddinger KJ et al.", "journal": "JAMA Netw Open", "year": 2022,
        "study_type": "cohort", "evidence_grade": "B", "pillar_id": 6,
        "summary": "Mendelian randomization study showing alcohol at all levels associated with increased cardiovascular risk, challenging the J-curve hypothesis.",
        "key_finding": "Using genetic instruments, alcohol consumption at all levels associated with increased cardiovascular risk.",
        "effect_size": "1.3-fold hypertension; 1.4-fold CAD per 1-SD increase",
        "sample_size": 371463, "population": "UK Biobank participants",
        "dose_response": "Exponential risk increases with heavier consumption; no protective threshold.",
        "causation_note": "Mendelian randomization reduces confounding; supports causal relationship.",
        "tags": "substance_avoidance,alcohol,cardiovascular,Mendelian_randomization,no_safe_level",
        "url": "https://pubmed.ncbi.nlm.nih.gov/35333364/",
        "journal_tier": "q1", "domain": "cardio_metabolic",
    },
    {
        "pmid": "32803250", "doi": "10.1093/ntr/ntaa156",
        "title": "Cigarette Smoking Reduction and Health Risks: A Systematic Review and Meta-analysis",
        "authors": "Chang JT et al.", "journal": "Nicotine Tob Res", "year": 2021,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 6,
        "summary": "Meta-analysis showing smoking reduction helps but complete cessation remains most effective for reducing cancer and CVD risk.",
        "key_finding": "Reducing from heavy to light smoking decreased lung cancer risk by 40% and CVD risk by 22%.",
        "effect_size": "Lung cancer RR 0.60 (95% CI 0.49-0.72); CVD RR 0.78",
        "sample_size": None, "population": "19 studies (4 case-control, 15 cohort)",
        "dose_response": "Complete cessation > reduction; even light smoking carries residual risk.",
        "causation_note": None,
        "tags": "substance_avoidance,smoking,cessation,lung_cancer,cardiovascular",
        "url": "https://pubmed.ncbi.nlm.nih.gov/32803250/",
        "journal_tier": "q1", "domain": "toxicology",
    },
    {
        "pmid": "26188829", "doi": "10.1016/j.ijcard.2015.07.011",
        "title": "Risk of all-cause mortality and cardiovascular disease associated with secondhand smoke exposure",
        "authors": "Lv X et al.", "journal": "Int J Cardiol", "year": 2015,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 6,
        "summary": "Meta-analysis showing secondhand smoke exposure increases mortality and CVD risk in never smokers.",
        "key_finding": "Secondhand smoke increased all-cause mortality by 18% and cardiovascular disease by 23% in never smokers.",
        "effect_size": "Mortality RR 1.18 (95% CI 1.10-1.27); CVD RR 1.23 (95% CI 1.16-1.31)",
        "sample_size": None, "population": "40 studies (23 prospective, 17 case-control)",
        "dose_response": None,
        "causation_note": None,
        "tags": "substance_avoidance,secondhand_smoke,mortality,cardiovascular",
        "url": "https://pubmed.ncbi.nlm.nih.gov/26188829/",
        "journal_tier": "q1", "domain": "cardio_metabolic",
    },
    {
        "pmid": "30758486", "doi": "10.1001/jamapsychiatry.2018.4500",
        "title": "Association of Cannabis Use in Adolescence and Risk of Depression, Anxiety, and Suicidality in Young Adulthood",
        "authors": "Gobbi G et al.", "journal": "JAMA Psychiatry", "year": 2019,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 6,
        "summary": "Meta-analysis showing adolescent cannabis use significantly increases risk of depression, anxiety, and suicidality.",
        "key_finding": "Adolescent cannabis use associated with 37% increased depression risk and 3.46-fold increased suicide attempt risk.",
        "effect_size": "Depression OR 1.37; Suicidal ideation OR 1.50; Suicide attempt OR 3.46",
        "sample_size": 23317, "population": "Adolescents/young adults (11 studies)",
        "dose_response": None,
        "causation_note": "Observational; developing brain vulnerability proposed as mechanism.",
        "tags": "substance_avoidance,cannabis,depression,suicide,mental_health,adolescent",
        "url": "https://pubmed.ncbi.nlm.nih.gov/30758486/",
        "journal_tier": "elite", "domain": "toxicology",
    },
    {
        "pmid": "23347102", "doi": "10.1111/acer.12006",
        "title": "Alcohol and sleep I: effects on normal sleep",
        "authors": "Ebrahim IO et al.", "journal": "Alcohol Clin Exp Res", "year": 2013,
        "study_type": "systematic_review", "evidence_grade": "A", "pillar_id": 6,
        "summary": "Systematic review establishing that alcohol disrupts sleep architecture at all doses despite reducing sleep onset latency.",
        "key_finding": "Alcohol reduces sleep onset latency but disrupts second-half sleep and significantly reduces REM sleep at all doses.",
        "effect_size": None,
        "sample_size": None, "population": "Healthy volunteers, all known studies reviewed",
        "dose_response": "Even low doses affect REM sleep; moderate-to-high doses cause significant second-half disruption.",
        "causation_note": "Experimental evidence supports causal mechanism.",
        "tags": "substance_avoidance,alcohol,sleep,REM,sleep_quality",
        "url": "https://pubmed.ncbi.nlm.nih.gov/23347102/",
        "journal_tier": "q1", "domain": "toxicology",
    },
    {
        "pmid": "37684424", "doi": "10.1007/s12072-023-10584-z",
        "title": "How does alcohol use impact morbidity and mortality of liver cirrhosis?",
        "authors": "Llamosas-Falcon L et al.", "journal": "Hepatol Int", "year": 2023,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 6,
        "summary": "Dose-response meta-analysis showing exponential liver cirrhosis risk with alcohol consumption.",
        "key_finding": "25 g/day alcohol associated with 2.65-fold mortality; 100 g/day with 16.38-fold mortality from liver cirrhosis.",
        "effect_size": "RR 2.65 at 25 g/day; RR 16.38 at 100 g/day",
        "sample_size": 5122534, "population": "44 studies + 1 secondary source",
        "dose_response": "Non-linear: risk accelerates exponentially with dose, especially for mortality vs morbidity.",
        "causation_note": None,
        "tags": "substance_avoidance,alcohol,liver_cirrhosis,liver_disease,dose_response",
        "url": "https://pubmed.ncbi.nlm.nih.gov/37684424/",
        "journal_tier": "q1", "domain": "toxicology",
    },
    {
        "pmid": "17573335", "doi": "10.1093/aje/kwm116",
        "title": "Smoking as a risk factor for dementia and cognitive decline: a meta-analysis of prospective studies",
        "authors": "Anstey KJ et al.", "journal": "Am J Epidemiol", "year": 2007,
        "study_type": "meta_analysis", "evidence_grade": "A", "pillar_id": 6,
        "summary": "Meta-analysis showing current smoking significantly increases risk of Alzheimer's disease and vascular dementia.",
        "key_finding": "Current smokers had 79% increased risk of Alzheimer's disease and 78% increased risk of vascular dementia.",
        "effect_size": "Alzheimer's RR 1.79 (95% CI 1.43-2.23); Vascular dementia RR 1.78 (95% CI 1.28-2.47)",
        "sample_size": 26374, "population": "19 prospective studies",
        "dose_response": None,
        "causation_note": "Observational; vascular mechanisms and oxidative stress proposed as causal pathways.",
        "tags": "substance_avoidance,smoking,dementia,cognitive_decline,Alzheimer",
        "url": "https://pubmed.ncbi.nlm.nih.gov/17573335/",
        "journal_tier": "q1", "domain": "toxicology",
    },
]
