"""Curated strength training exercise library.

50 exercises organized by muscle group with execution cues,
common mistakes, and equipment requirements.
"""

# ── Muscle Groups ────────────────────────────────────────────────────────────

MUSCLE_GROUPS = {
    "chest": {"label": "Chest", "icon": "&#128170;", "color": "#D93025"},
    "back": {"label": "Back", "icon": "&#129470;", "color": "#1A73E8"},
    "shoulders": {"label": "Shoulders", "icon": "&#9889;", "color": "#E8710A"},
    "biceps": {"label": "Biceps", "icon": "&#128170;", "color": "#7B1FA2"},
    "triceps": {"label": "Triceps", "icon": "&#128170;", "color": "#007B83"},
    "legs": {"label": "Legs", "icon": "&#129461;", "color": "#1E8E3E"},
    "glutes": {"label": "Glutes", "icon": "&#127939;", "color": "#D01884"},
    "core": {"label": "Core", "icon": "&#129526;", "color": "#F9AB00"},
}

EQUIPMENT_TYPES = {
    "bodyweight": {"label": "Bodyweight", "icon": "&#128587;"},
    "dumbbells": {"label": "Dumbbells", "icon": "&#127947;"},
    "barbell": {"label": "Barbell", "icon": "&#127947;"},
    "cable": {"label": "Cable Machine", "icon": "&#128260;"},
    "machine": {"label": "Machine", "icon": "&#9881;"},
    "band": {"label": "Resistance Band", "icon": "&#127992;"},
    "kettlebell": {"label": "Kettlebell", "icon": "&#127947;"},
}

DIFFICULTY_LEVELS = {
    "beginner": {"label": "Beginner", "color": "#1E8E3E"},
    "intermediate": {"label": "Intermediate", "color": "#F9AB00"},
    "advanced": {"label": "Advanced", "color": "#D93025"},
}

# ── Exercise Library ─────────────────────────────────────────────────────────

EXERCISE_LIBRARY = [
    # ──────────────── CHEST ────────────────
    {
        "id": "barbell_bench_press",
        "name": "Barbell Bench Press",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "type": "compound",
        "description": "Lie on a flat bench, grip the bar slightly wider than shoulder-width. Lower the bar to mid-chest with elbows at ~75 degrees, then press up to full extension.",
        "cues": "Retract shoulder blades, plant feet firmly, maintain natural arch. Drive through feet as you press.",
        "mistakes": "Flaring elbows to 90 degrees increases shoulder injury risk. Bouncing the bar off the chest removes tension.",
        "sets_reps": "3-4 sets of 6-10 reps",
        "video_search": "barbell bench press form",
    },
    {
        "id": "dumbbell_bench_press",
        "name": "Dumbbell Bench Press",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "type": "compound",
        "description": "Lie on a flat bench holding dumbbells at chest level. Press up until arms are extended, then lower with control.",
        "cues": "Keep wrists neutral, lower until upper arms are parallel to the floor. Squeeze chest at the top.",
        "mistakes": "Letting dumbbells drift too far apart at the bottom. Using momentum instead of controlled movement.",
        "sets_reps": "3-4 sets of 8-12 reps",
        "video_search": "dumbbell bench press form",
    },
    {
        "id": "incline_dumbbell_press",
        "name": "Incline Dumbbell Press",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "type": "compound",
        "description": "Set bench to 30-45 degrees. Press dumbbells from shoulder level upward, focusing on the upper chest.",
        "cues": "Keep back flat against the bench. Don't let elbows drop too far below shoulder level.",
        "mistakes": "Setting the incline too steep (turns into a shoulder press). Arching the lower back excessively.",
        "sets_reps": "3 sets of 8-12 reps",
        "video_search": "incline dumbbell press form",
    },
    {
        "id": "push_up",
        "name": "Push-Up",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders", "core"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "type": "compound",
        "description": "Start in a plank position with hands slightly wider than shoulders. Lower your chest to the floor, then push back up.",
        "cues": "Keep body in a straight line from head to heels. Engage core throughout. Elbows at 45 degrees.",
        "mistakes": "Sagging hips or piking up. Flaring elbows straight out to the sides.",
        "sets_reps": "3 sets of 10-20 reps",
        "video_search": "proper push up form",
    },
    {
        "id": "cable_chest_fly",
        "name": "Cable Chest Fly",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders"],
        "equipment": "cable",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Stand between cable pulleys set at shoulder height. With a slight bend in elbows, bring handles together in front of your chest.",
        "cues": "Lead with elbows, not hands. Squeeze chest hard at the peak contraction. Control the eccentric.",
        "mistakes": "Bending elbows too much (turning it into a press). Using too much weight and losing form.",
        "sets_reps": "3 sets of 12-15 reps",
        "video_search": "cable chest fly form",
    },
    {
        "id": "dips_chest",
        "name": "Chest Dips",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "type": "compound",
        "description": "On parallel bars, lean your torso forward ~30 degrees. Lower until upper arms are parallel to the floor, then press up.",
        "cues": "Lean forward to emphasize chest. Flare elbows slightly. Don't lock out aggressively at the top.",
        "mistakes": "Staying too upright (shifts load to triceps). Going too deep without adequate shoulder mobility.",
        "sets_reps": "3 sets of 8-12 reps",
        "video_search": "chest dips form",
    },

    # ──────────────── BACK ────────────────
    {
        "id": "barbell_row",
        "name": "Barbell Bent-Over Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "core"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "type": "compound",
        "description": "Hinge at the hips with knees slightly bent, back flat. Pull the barbell to your lower chest/upper abdomen.",
        "cues": "Drive elbows back, squeeze shoulder blades together at the top. Keep torso angle consistent.",
        "mistakes": "Rounding the lower back. Using momentum by jerking the torso upright.",
        "sets_reps": "3-4 sets of 6-10 reps",
        "video_search": "barbell bent over row form",
    },
    {
        "id": "pull_up",
        "name": "Pull-Up",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "core"],
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "type": "compound",
        "description": "Hang from a bar with overhand grip slightly wider than shoulders. Pull yourself up until chin clears the bar.",
        "cues": "Initiate by depressing shoulder blades. Drive elbows down toward your hips. Full range of motion.",
        "mistakes": "Kipping or swinging. Not going to full extension at the bottom (partial reps).",
        "sets_reps": "3 sets of 5-12 reps",
        "video_search": "pull up proper form",
    },
    {
        "id": "lat_pulldown",
        "name": "Lat Pulldown",
        "muscle_group": "back",
        "secondary_muscles": ["biceps"],
        "equipment": "cable",
        "difficulty": "beginner",
        "type": "compound",
        "description": "Sit at a lat pulldown machine, grip the bar wider than shoulder-width. Pull the bar to your upper chest.",
        "cues": "Lean back slightly, drive elbows down and back. Control the weight on the way up.",
        "mistakes": "Pulling behind the neck (shoulder injury risk). Leaning back excessively and using momentum.",
        "sets_reps": "3-4 sets of 8-12 reps",
        "video_search": "lat pulldown form",
    },
    {
        "id": "dumbbell_row",
        "name": "Single-Arm Dumbbell Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "core"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "type": "compound",
        "description": "Place one knee and hand on a bench. Row a dumbbell from a dead hang to your hip with the other arm.",
        "cues": "Keep hips square to the floor. Pull to your hip, not your armpit. Squeeze the lat at the top.",
        "mistakes": "Rotating the torso to lift heavier weight. Shrugging the shoulder up instead of pulling with the lat.",
        "sets_reps": "3 sets of 8-12 reps per side",
        "video_search": "single arm dumbbell row form",
    },
    {
        "id": "seated_cable_row",
        "name": "Seated Cable Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps"],
        "equipment": "cable",
        "difficulty": "beginner",
        "type": "compound",
        "description": "Sit at a cable row station with feet on the platform. Pull the handle to your lower chest while keeping torso upright.",
        "cues": "Keep chest up, squeeze shoulder blades together. Don't lean too far back or forward.",
        "mistakes": "Using excessive body momentum. Rounding the lower back during the stretch portion.",
        "sets_reps": "3 sets of 10-12 reps",
        "video_search": "seated cable row form",
    },
    {
        "id": "face_pull",
        "name": "Face Pull",
        "muscle_group": "back",
        "secondary_muscles": ["shoulders"],
        "equipment": "cable",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Set cable at face height with rope attachment. Pull toward your face, spreading the rope apart, with elbows high.",
        "cues": "External rotate at the end position. Squeeze rear delts and upper back. Keep elbows at shoulder height.",
        "mistakes": "Using too much weight and turning it into a row. Not pulling far enough back.",
        "sets_reps": "3 sets of 15-20 reps",
        "video_search": "face pull form",
    },

    # ──────────────── SHOULDERS ────────────────
    {
        "id": "overhead_press",
        "name": "Overhead Press",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps", "core"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "type": "compound",
        "description": "Stand with barbell at shoulder level, grip slightly wider than shoulders. Press overhead to full lockout.",
        "cues": "Brace core hard, squeeze glutes. Move your head through once the bar passes. Lock out directly overhead.",
        "mistakes": "Excessive lower back arch. Pressing the bar forward instead of straight up.",
        "sets_reps": "3-4 sets of 6-10 reps",
        "video_search": "overhead press barbell form",
    },
    {
        "id": "dumbbell_shoulder_press",
        "name": "Dumbbell Shoulder Press",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "type": "compound",
        "description": "Seated or standing, press dumbbells from shoulder level overhead until arms are fully extended.",
        "cues": "Keep core tight, don't flare ribs. Press in a slight arc, bringing dumbbells together at the top.",
        "mistakes": "Arching the back excessively. Not achieving full range of motion.",
        "sets_reps": "3 sets of 8-12 reps",
        "video_search": "dumbbell shoulder press form",
    },
    {
        "id": "lateral_raise",
        "name": "Lateral Raise",
        "muscle_group": "shoulders",
        "secondary_muscles": [],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Stand with dumbbells at your sides. Raise arms out to the sides until parallel with the floor, leading with the elbows.",
        "cues": "Slight bend in elbows. Lead with elbows, not hands. Pour water at the top (slight internal rotation).",
        "mistakes": "Using too much weight and swinging. Shrugging traps instead of isolating the medial delt.",
        "sets_reps": "3-4 sets of 12-15 reps",
        "video_search": "lateral raise proper form",
    },
    {
        "id": "rear_delt_fly",
        "name": "Rear Delt Fly",
        "muscle_group": "shoulders",
        "secondary_muscles": ["back"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Bend forward at the hips, arms hanging. Raise dumbbells out to the sides, squeezing rear delts.",
        "cues": "Keep chest up, slight bend in elbows. Focus on squeezing the shoulder blades together.",
        "mistakes": "Using momentum by swinging the torso. Lifting with the traps instead of rear delts.",
        "sets_reps": "3 sets of 12-15 reps",
        "video_search": "rear delt fly form",
    },
    {
        "id": "arnold_press",
        "name": "Arnold Press",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps"],
        "equipment": "dumbbells",
        "difficulty": "intermediate",
        "type": "compound",
        "description": "Start with dumbbells in front at chin level (palms facing you). Rotate and press overhead simultaneously.",
        "cues": "Smooth rotation throughout the press. Full lockout at the top. Control the descent.",
        "mistakes": "Rushing the rotation. Not going through the full range of motion.",
        "sets_reps": "3 sets of 8-12 reps",
        "video_search": "arnold press form",
    },

    # ──────────────── BICEPS ────────────────
    {
        "id": "barbell_curl",
        "name": "Barbell Curl",
        "muscle_group": "biceps",
        "secondary_muscles": [],
        "equipment": "barbell",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Stand with barbell at arm's length, underhand grip. Curl the weight up while keeping elbows pinned to your sides.",
        "cues": "Squeeze at the top. Lower under control (3-second eccentric). Keep upper arms stationary.",
        "mistakes": "Swinging the body to lift heavier weight. Moving elbows forward during the curl.",
        "sets_reps": "3 sets of 8-12 reps",
        "video_search": "barbell curl form",
    },
    {
        "id": "dumbbell_curl",
        "name": "Dumbbell Bicep Curl",
        "muscle_group": "biceps",
        "secondary_muscles": [],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Stand or sit holding dumbbells. Curl one or both dumbbells upward, supinating the wrist as you lift.",
        "cues": "Start with palms facing thighs, rotate to palms up as you curl. Full supination at the top.",
        "mistakes": "Using body momentum. Not fully extending at the bottom.",
        "sets_reps": "3 sets of 10-12 reps",
        "video_search": "dumbbell bicep curl form",
    },
    {
        "id": "hammer_curl",
        "name": "Hammer Curl",
        "muscle_group": "biceps",
        "secondary_muscles": [],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Curl dumbbells with a neutral grip (palms facing each other throughout). Targets the brachialis and brachioradialis.",
        "cues": "Keep elbows close to your body. Controlled movement both up and down.",
        "mistakes": "Flaring elbows out. Swinging the weight up.",
        "sets_reps": "3 sets of 10-12 reps",
        "video_search": "hammer curl form",
    },
    {
        "id": "incline_dumbbell_curl",
        "name": "Incline Dumbbell Curl",
        "muscle_group": "biceps",
        "secondary_muscles": [],
        "equipment": "dumbbells",
        "difficulty": "intermediate",
        "type": "isolation",
        "description": "Sit on an incline bench (45 degrees). Let arms hang, then curl up. The incline stretches the long head of the bicep.",
        "cues": "Keep shoulder blades pinned to the bench. Don't let elbows drift forward.",
        "mistakes": "Lifting the shoulders off the bench. Using a bench angle that's too steep.",
        "sets_reps": "3 sets of 10-12 reps",
        "video_search": "incline dumbbell curl form",
    },
    {
        "id": "concentration_curl",
        "name": "Concentration Curl",
        "muscle_group": "biceps",
        "secondary_muscles": [],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Sit with elbow braced against inner thigh. Curl the dumbbell up, focusing on peak contraction.",
        "cues": "Brace your elbow firmly. Squeeze hard at the top for 1-2 seconds. Slow eccentric.",
        "mistakes": "Using the shoulder to lift. Not bracing the elbow properly.",
        "sets_reps": "3 sets of 10-12 reps per arm",
        "video_search": "concentration curl form",
    },

    # ──────────────── TRICEPS ────────────────
    {
        "id": "tricep_pushdown",
        "name": "Tricep Cable Pushdown",
        "muscle_group": "triceps",
        "secondary_muscles": [],
        "equipment": "cable",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "At a cable station with a bar or rope attachment, push down from chest level to full arm extension.",
        "cues": "Keep elbows pinned at your sides. Squeeze triceps at the bottom. Control the return.",
        "mistakes": "Flaring elbows out. Leaning over the weight instead of standing upright.",
        "sets_reps": "3 sets of 10-15 reps",
        "video_search": "tricep pushdown form",
    },
    {
        "id": "overhead_tricep_extension",
        "name": "Overhead Tricep Extension",
        "muscle_group": "triceps",
        "secondary_muscles": [],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Hold a dumbbell overhead with both hands. Lower it behind your head by bending the elbows, then extend back up.",
        "cues": "Keep elbows close to your head pointing forward. Full stretch at the bottom, full lockout at the top.",
        "mistakes": "Flaring elbows out wide. Arching the lower back.",
        "sets_reps": "3 sets of 10-12 reps",
        "video_search": "overhead tricep extension form",
    },
    {
        "id": "skull_crusher",
        "name": "Skull Crusher (Lying Tricep Extension)",
        "muscle_group": "triceps",
        "secondary_muscles": [],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "type": "isolation",
        "description": "Lie on a bench with EZ bar or barbell extended overhead. Lower the bar toward your forehead by bending only at the elbows.",
        "cues": "Keep upper arms vertical and stationary. Lower to forehead level, then extend. Control is critical.",
        "mistakes": "Moving the upper arms (turning it into a pullover). Going too heavy and losing control.",
        "sets_reps": "3 sets of 8-12 reps",
        "video_search": "skull crusher form",
    },
    {
        "id": "close_grip_bench",
        "name": "Close-Grip Bench Press",
        "muscle_group": "triceps",
        "secondary_muscles": ["chest", "shoulders"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "type": "compound",
        "description": "Bench press with hands shoulder-width apart (or slightly narrower). Lower the bar to lower chest, then press up.",
        "cues": "Tuck elbows close to the body. Focus on tricep contraction during the press.",
        "mistakes": "Grip too narrow (wrist strain). Flaring elbows out (becomes regular bench).",
        "sets_reps": "3-4 sets of 8-10 reps",
        "video_search": "close grip bench press form",
    },
    {
        "id": "diamond_push_up",
        "name": "Diamond Push-Up",
        "muscle_group": "triceps",
        "secondary_muscles": ["chest", "shoulders"],
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "type": "compound",
        "description": "Push-up with hands close together forming a diamond shape with thumbs and index fingers. Lower chest to hands.",
        "cues": "Keep elbows close to your body. Maintain a straight line from head to heels.",
        "mistakes": "Flaring elbows out. Letting hips sag.",
        "sets_reps": "3 sets of 10-15 reps",
        "video_search": "diamond push up form",
    },

    # ──────────────── LEGS ────────────────
    {
        "id": "barbell_squat",
        "name": "Barbell Back Squat",
        "muscle_group": "legs",
        "secondary_muscles": ["glutes", "core"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "type": "compound",
        "description": "Bar on upper back, feet shoulder-width apart. Squat down until thighs are at least parallel to the floor, then stand.",
        "cues": "Brace core, push knees out over toes. Drive through whole foot. Chest up throughout.",
        "mistakes": "Knees caving inward. Rounding the lower back. Not hitting parallel depth.",
        "sets_reps": "3-4 sets of 5-8 reps",
        "video_search": "barbell back squat form",
    },
    {
        "id": "goblet_squat",
        "name": "Goblet Squat",
        "muscle_group": "legs",
        "secondary_muscles": ["glutes", "core"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "type": "compound",
        "description": "Hold a dumbbell or kettlebell at chest level. Squat down with elbows between your knees, then stand back up.",
        "cues": "Keep chest up and elbows inside knees. Sit back and down. Full depth if mobility allows.",
        "mistakes": "Leaning forward too much. Heels lifting off the ground.",
        "sets_reps": "3 sets of 10-15 reps",
        "video_search": "goblet squat form",
    },
    {
        "id": "romanian_deadlift",
        "name": "Romanian Deadlift",
        "muscle_group": "legs",
        "secondary_muscles": ["glutes", "back"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "type": "compound",
        "description": "Hold barbell at hip level. Hinge at the hips, pushing them back, lowering the bar along your legs. Feel the hamstring stretch.",
        "cues": "Keep bar close to your body. Slight knee bend. Push hips back, not down. Flat back throughout.",
        "mistakes": "Rounding the lower back. Bending knees too much (turning it into a squat).",
        "sets_reps": "3-4 sets of 8-12 reps",
        "video_search": "romanian deadlift form",
    },
    {
        "id": "leg_press",
        "name": "Leg Press",
        "muscle_group": "legs",
        "secondary_muscles": ["glutes"],
        "equipment": "machine",
        "difficulty": "beginner",
        "type": "compound",
        "description": "Sit in the leg press machine with feet shoulder-width on the platform. Lower the weight by bending knees, then press back up.",
        "cues": "Don't lock knees at the top. Lower until knees are at ~90 degrees. Push through the whole foot.",
        "mistakes": "Lowering too far and lifting the lower back off the pad. Locking knees at full extension.",
        "sets_reps": "3-4 sets of 10-15 reps",
        "video_search": "leg press form",
    },
    {
        "id": "walking_lunge",
        "name": "Walking Lunge",
        "muscle_group": "legs",
        "secondary_muscles": ["glutes", "core"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "type": "compound",
        "description": "Step forward into a lunge position (both knees at ~90 degrees). Push off the front foot and step into the next lunge.",
        "cues": "Keep torso upright. Front knee tracks over the toe. Control each step.",
        "mistakes": "Knee extending past the toes excessively. Leaning forward. Taking too short of steps.",
        "sets_reps": "3 sets of 12-16 steps total",
        "video_search": "walking lunge form",
    },
    {
        "id": "leg_extension",
        "name": "Leg Extension",
        "muscle_group": "legs",
        "secondary_muscles": [],
        "equipment": "machine",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Sit in the leg extension machine. Extend your legs to straighten the knees, then lower with control.",
        "cues": "Squeeze the quads at the top. 2-second hold at full extension. Slow and controlled eccentric.",
        "mistakes": "Using momentum to swing the weight. Hyperextending the knees.",
        "sets_reps": "3 sets of 12-15 reps",
        "video_search": "leg extension form",
    },
    {
        "id": "leg_curl",
        "name": "Lying Leg Curl",
        "muscle_group": "legs",
        "secondary_muscles": [],
        "equipment": "machine",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Lie face down on the leg curl machine. Curl your heels toward your glutes, then lower slowly.",
        "cues": "Keep hips pressed against the pad. Squeeze hamstrings at the top. Slow eccentric.",
        "mistakes": "Lifting hips off the pad. Using too much weight and losing range of motion.",
        "sets_reps": "3 sets of 10-12 reps",
        "video_search": "lying leg curl form",
    },
    {
        "id": "calf_raise",
        "name": "Standing Calf Raise",
        "muscle_group": "legs",
        "secondary_muscles": [],
        "equipment": "machine",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Stand on a calf raise machine or step edge. Rise up onto your toes, then lower your heels below the platform for a full stretch.",
        "cues": "Full range of motion is key. 2-second pause at the top. Slow stretch at the bottom.",
        "mistakes": "Bouncing at the bottom. Partial range of motion.",
        "sets_reps": "4 sets of 12-20 reps",
        "video_search": "calf raise form",
    },

    # ──────────────── GLUTES ────────────────
    {
        "id": "hip_thrust",
        "name": "Barbell Hip Thrust",
        "muscle_group": "glutes",
        "secondary_muscles": ["legs"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "type": "compound",
        "description": "Sit on the floor with upper back against a bench, barbell across hips. Drive hips up until your body forms a straight line.",
        "cues": "Chin tucked, drive through heels. Squeeze glutes hard at the top for 2 seconds. Don't hyperextend.",
        "mistakes": "Hyperextending the lower back at the top. Not achieving full hip extension.",
        "sets_reps": "3-4 sets of 8-12 reps",
        "video_search": "barbell hip thrust form",
    },
    {
        "id": "glute_bridge",
        "name": "Glute Bridge",
        "muscle_group": "glutes",
        "secondary_muscles": ["legs", "core"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "type": "compound",
        "description": "Lie on your back, feet flat on the floor near your glutes. Drive hips up by squeezing your glutes.",
        "cues": "Push through heels. Squeeze glutes at the top. Keep ribs down (don't arch the back).",
        "mistakes": "Pushing through the toes instead of heels. Hyperextending the lower back.",
        "sets_reps": "3 sets of 15-20 reps",
        "video_search": "glute bridge form",
    },
    {
        "id": "bulgarian_split_squat",
        "name": "Bulgarian Split Squat",
        "muscle_group": "glutes",
        "secondary_muscles": ["legs"],
        "equipment": "dumbbells",
        "difficulty": "intermediate",
        "type": "compound",
        "description": "Stand with one foot elevated on a bench behind you. Lower into a single-leg squat, then drive back up.",
        "cues": "Keep torso upright. Front shin roughly vertical. Push through the front heel.",
        "mistakes": "Leaning too far forward. Placing the back foot too close to the bench.",
        "sets_reps": "3 sets of 8-12 reps per leg",
        "video_search": "bulgarian split squat form",
    },
    {
        "id": "cable_pull_through",
        "name": "Cable Pull-Through",
        "muscle_group": "glutes",
        "secondary_muscles": ["legs"],
        "equipment": "cable",
        "difficulty": "beginner",
        "type": "compound",
        "description": "Face away from a low cable pulley, rope between legs. Hinge at the hips and pull through by squeezing glutes to stand tall.",
        "cues": "Think of pushing your hips back, then snapping them forward. Keep arms straight throughout.",
        "mistakes": "Squatting instead of hinging. Pulling with the arms.",
        "sets_reps": "3 sets of 12-15 reps",
        "video_search": "cable pull through form",
    },

    # ──────────────── CORE ────────────────
    {
        "id": "plank",
        "name": "Plank",
        "muscle_group": "core",
        "secondary_muscles": ["shoulders"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Hold a push-up position on forearms or hands with body in a straight line from head to heels.",
        "cues": "Brace core as if bracing for a punch. Squeeze glutes. Don't hold breath — breathe normally.",
        "mistakes": "Sagging hips or piking up. Looking up instead of down (neck alignment).",
        "sets_reps": "3 sets of 30-60 seconds",
        "video_search": "plank proper form",
    },
    {
        "id": "dead_bug",
        "name": "Dead Bug",
        "muscle_group": "core",
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "type": "isolation",
        "description": "Lie on your back with arms extended up and knees at 90 degrees. Alternately lower opposite arm and leg while keeping lower back flat.",
        "cues": "Press lower back into the floor throughout. Exhale as you extend. Move slowly and controlled.",
        "mistakes": "Lower back arching off the floor. Moving too quickly.",
        "sets_reps": "3 sets of 10-12 reps per side",
        "video_search": "dead bug exercise form",
    },
    {
        "id": "pallof_press",
        "name": "Pallof Press",
        "muscle_group": "core",
        "secondary_muscles": [],
        "equipment": "cable",
        "difficulty": "intermediate",
        "type": "isolation",
        "description": "Stand perpendicular to a cable machine, hold the handle at chest level. Press arms straight out, resisting rotation.",
        "cues": "Stand tall, brace core. Press slowly and hold at full extension. Resist the cable pulling you to rotate.",
        "mistakes": "Rotating the torso toward the cable. Not bracing the core.",
        "sets_reps": "3 sets of 10-12 reps per side",
        "video_search": "pallof press form",
    },
    {
        "id": "hanging_leg_raise",
        "name": "Hanging Leg Raise",
        "muscle_group": "core",
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "difficulty": "advanced",
        "type": "isolation",
        "description": "Hang from a pull-up bar. Raise your legs to parallel (or higher) by curling the pelvis, then lower with control.",
        "cues": "Initiate with a posterior pelvic tilt. Control the swing. Don't just lift legs — curl the pelvis.",
        "mistakes": "Swinging for momentum. Only lifting from the hip flexors without engaging abs.",
        "sets_reps": "3 sets of 8-12 reps",
        "video_search": "hanging leg raise form",
    },
    {
        "id": "ab_wheel_rollout",
        "name": "Ab Wheel Rollout",
        "muscle_group": "core",
        "secondary_muscles": ["shoulders"],
        "equipment": "bodyweight",
        "difficulty": "advanced",
        "type": "isolation",
        "description": "Kneel with an ab wheel. Roll forward extending your body, then pull back using your core. Start with partial range.",
        "cues": "Brace core hard, tuck pelvis slightly. Don't let your lower back collapse. Pull back with your abs.",
        "mistakes": "Collapsing the lower back. Going too far out before building strength.",
        "sets_reps": "3 sets of 8-12 reps",
        "video_search": "ab wheel rollout form",
    },
    {
        "id": "cable_woodchop",
        "name": "Cable Woodchop",
        "muscle_group": "core",
        "secondary_muscles": ["shoulders"],
        "equipment": "cable",
        "difficulty": "intermediate",
        "type": "compound",
        "description": "Set cable high or low. Rotate your torso diagonally, pulling the cable across your body. Control the return.",
        "cues": "Power comes from the hips and core rotation, not the arms. Keep arms relatively straight.",
        "mistakes": "Pulling with the arms instead of rotating the torso. Moving too fast.",
        "sets_reps": "3 sets of 10-12 reps per side",
        "video_search": "cable woodchop form",
    },
]

# ── Helper functions ─────────────────────────────────────────────────────────

def get_exercises_by_muscle(muscle_group):
    """Return exercises filtered by muscle group."""
    return [e for e in EXERCISE_LIBRARY if e["muscle_group"] == muscle_group]


def get_exercises_by_equipment(equipment):
    """Return exercises filtered by equipment."""
    return [e for e in EXERCISE_LIBRARY if e["equipment"] == equipment]


def get_exercises_by_difficulty(difficulty):
    """Return exercises filtered by difficulty."""
    return [e for e in EXERCISE_LIBRARY if e["difficulty"] == difficulty]


def search_exercises(query):
    """Search exercises by name or description."""
    q = query.lower()
    return [
        e for e in EXERCISE_LIBRARY
        if q in e["name"].lower()
        or q in e["description"].lower()
        or q in e["muscle_group"].lower()
        or any(q in m for m in e["secondary_muscles"])
    ]
