"""Science-backed daily protocols organized by ACLM pillar.

Each protocol references real PubMed-verified studies from evidence_data.py
via linked_pmids. Fields match the `protocols` DB table schema.
"""

PROTOCOL_LIBRARY = [
    # ══════════════════════════════════════════════════════════════════════════
    # PILLAR 1: NUTRITION
    # ══════════════════════════════════════════════════════════════════════════
    {
        "pillar_id": 1,
        "name": "Mediterranean Meal Template",
        "description": "Structure at least one meal per day around the Mediterranean pattern: vegetables as the base, extra-virgin olive oil, whole grains, legumes, nuts, and herbs/spices.",
        "timing": "Lunch or Dinner",
        "duration": "20-30 min",
        "frequency": "daily",
        "difficulty": 2,
        "mechanism": "The Mediterranean dietary pattern reduces systemic inflammation (CRP, IL-6), improves endothelial function, and modulates the gut microbiome toward anti-inflammatory species. Rich in polyphenols, monounsaturated fats, and fiber.",
        "expected_benefit": "30% reduction in cardiovascular events (PREDIMED); improved glycemic control; reduced all-cause mortality risk.",
        "contraindications": "Nut allergies (substitute seeds). Those on warfarin should maintain consistent vitamin K intake from greens.",
        "sort_order": 1,
        "linked_pmids": ["29897866", "33641343"],
    },
    {
        "pillar_id": 1,
        "name": "Daily Fiber Target (30g+)",
        "description": "Track and aim for at least 30g of dietary fiber per day from whole food sources: legumes, whole grains, vegetables, fruits, nuts, and seeds.",
        "timing": "Throughout the day",
        "duration": "N/A",
        "frequency": "daily",
        "difficulty": 2,
        "mechanism": "Dietary fiber feeds beneficial gut bacteria (Bifidobacteria, Lactobacillus), producing short-chain fatty acids (butyrate, propionate) that reduce intestinal permeability and systemic inflammation. Also improves satiety and glycemic regulation.",
        "expected_benefit": "15-30% reduction in all-cause mortality, coronary heart disease, stroke, type 2 diabetes, and colorectal cancer per 8g/day increase in fiber intake.",
        "contraindications": "Increase gradually to avoid GI discomfort. Those with IBD flares may need to moderate insoluble fiber.",
        "sort_order": 2,
        "linked_pmids": ["30638909", "38363072"],
    },
    {
        "pillar_id": 1,
        "name": "Plant Diversity Challenge (30/week)",
        "description": "Eat at least 30 different plant species per week. Count each unique vegetable, fruit, grain, legume, nut, seed, herb, and spice.",
        "timing": "Anytime",
        "duration": "N/A",
        "frequency": "daily",
        "difficulty": 2,
        "mechanism": "Greater plant diversity provides a wider array of prebiotic substrates, polyphenols, and micronutrients, promoting alpha-diversity in gut microbiota. The American Gut Project found 30+ plants/week was the strongest predictor of microbial diversity.",
        "expected_benefit": "Greater gut microbiome diversity, improved immune function, better nutrient coverage, reduced chronic disease risk.",
        "contraindications": "None significant. Those with food sensitivities should focus on tolerated species.",
        "sort_order": 3,
        "linked_pmids": ["28424256", "35672940"],
    },
    {
        "pillar_id": 1,
        "name": "Omega-3 Rich Meal (3x/week)",
        "description": "Include omega-3-rich foods 3 times per week: fatty fish (salmon, sardines, mackerel), walnuts, chia seeds, flaxseeds, or hemp seeds.",
        "timing": "Lunch or Dinner",
        "duration": "N/A",
        "frequency": "3x per week",
        "difficulty": 1,
        "mechanism": "EPA and DHA omega-3 fatty acids are incorporated into cell membranes, producing anti-inflammatory resolvins and protectins. They reduce triglycerides, lower blood pressure, and decrease platelet aggregation.",
        "expected_benefit": "Reduced cardiovascular mortality, lower triglycerides, improved inflammatory markers, potential cognitive benefits.",
        "contraindications": "Fish allergy (use plant-based sources). High-dose supplements may interact with anticoagulants.",
        "sort_order": 4,
        "linked_pmids": ["32114706", "28338764"],
    },
    # ══════════════════════════════════════════════════════════════════════════
    # PILLAR 2: PHYSICAL ACTIVITY
    # ══════════════════════════════════════════════════════════════════════════
    {
        "pillar_id": 2,
        "name": "Morning Sunlight Walk",
        "description": "Walk outdoors for 10-20 minutes within 1 hour of waking, exposing eyes to natural sunlight (no sunglasses). Combine light exposure with light-to-moderate walking.",
        "timing": "Morning (within 1h of waking)",
        "duration": "10-20 min",
        "frequency": "daily",
        "difficulty": 1,
        "mechanism": "Morning light exposure activates melanopsin-containing intrinsically photosensitive retinal ganglion cells (ipRGCs) that signal the suprachiasmatic nucleus. This anchors the circadian clock, triggers a healthy cortisol rise, and programs melatonin onset ~14-16 hours later. Walking adds movement benefits.",
        "expected_benefit": "Better circadian alignment, improved sleep onset, enhanced daytime alertness, mood improvement, added steps toward daily movement goal.",
        "contraindications": "Use sunscreen for UV protection on extended walks. Those with photosensitivity conditions should consult their physician.",
        "sort_order": 1,
        "linked_pmids": ["27743803", "31434697"],
    },
    {
        "pillar_id": 2,
        "name": "Post-Meal Walk (10 min)",
        "description": "Take a 10-15 minute walk within 30 minutes of finishing a meal, ideally after the largest meal of the day.",
        "timing": "After meals",
        "duration": "10-15 min",
        "frequency": "daily",
        "difficulty": 1,
        "mechanism": "Light walking after eating enhances gastric motility and skeletal muscle glucose uptake via non-insulin-dependent GLUT4 translocation. This reduces postprandial glucose spikes by 30-50%, lessening the glycemic excursion and subsequent insulin demand.",
        "expected_benefit": "Significant reduction in postprandial glucose peaks, improved HbA1c over time, better digestion, manageable daily step accumulation.",
        "contraindications": "None significant. Adjust intensity for those with mobility limitations.",
        "sort_order": 2,
        "linked_pmids": ["25715415", "37555441"],
    },
    {
        "pillar_id": 2,
        "name": "Zone 2 Cardio Session",
        "description": "Perform 30-45 minutes of steady-state cardio at Zone 2 intensity (can hold a conversation, nasal breathing, 60-70% max HR). Options: brisk walking, easy cycling, swimming, elliptical.",
        "timing": "Morning or Afternoon",
        "duration": "30-45 min",
        "frequency": "3-4x per week",
        "difficulty": 2,
        "mechanism": "Zone 2 training preferentially develops mitochondrial density and function in Type I muscle fibers, enhancing fat oxidation capacity and lactate clearance. Improves cardiovascular efficiency (stroke volume, capillary density) without excessive sympathetic stress.",
        "expected_benefit": "Enhanced aerobic base, improved metabolic flexibility, reduced resting heart rate, better body composition, longevity benefits.",
        "contraindications": "Those with cardiovascular conditions should get medical clearance and monitor heart rate. Start with shorter sessions if deconditioned.",
        "sort_order": 3,
        "linked_pmids": ["35247352", "26092138"],
    },
    {
        "pillar_id": 2,
        "name": "Movement Snacks (Hourly)",
        "description": "Break up prolonged sitting every 45-60 minutes with 2-5 minutes of light activity: bodyweight squats, calf raises, walking, stretching, or stair climbing.",
        "timing": "Throughout the day",
        "duration": "2-5 min each",
        "frequency": "daily",
        "difficulty": 1,
        "mechanism": "Prolonged sitting impairs endothelial function and reduces lipoprotein lipase activity within hours. Brief activity bouts restore blood flow, reactivate postural muscles, and improve glucose disposal. Even standing transitions provide measurable metabolic benefit.",
        "expected_benefit": "Reduced mortality risk from sedentary behavior, improved glucose regulation, better focus and energy, reduced musculoskeletal stiffness.",
        "contraindications": "None. Adapt movements to ability level.",
        "sort_order": 4,
        "linked_pmids": ["35599175", "27475271"],
    },
    {
        "pillar_id": 2,
        "name": "Resistance Training Session",
        "description": "Perform 30-45 minutes of resistance training targeting all major muscle groups. Include compound movements: squats, hinges, presses, pulls, and carries.",
        "timing": "Morning or Afternoon",
        "duration": "30-45 min",
        "frequency": "2-3x per week",
        "difficulty": 3,
        "mechanism": "Resistance training stimulates muscle protein synthesis via mTOR pathway activation, increases GLUT4 expression for improved glucose uptake, enhances bone mineral density through mechanotransduction, and releases myokines (IL-6, irisin) with systemic anti-inflammatory effects.",
        "expected_benefit": "Increased lean mass and strength, improved insulin sensitivity, reduced all-cause mortality (10-17% risk reduction), better bone density, enhanced functional capacity.",
        "contraindications": "Those with acute injuries, uncontrolled hypertension, or recent surgery should consult physician. Start with bodyweight or light loads if untrained.",
        "sort_order": 5,
        "linked_pmids": ["26243014", "38355154"],
    },
    # ══════════════════════════════════════════════════════════════════════════
    # PILLAR 3: SLEEP
    # ══════════════════════════════════════════════════════════════════════════
    {
        "pillar_id": 3,
        "name": "Consistent Sleep Schedule",
        "description": "Go to bed and wake up within a 30-minute window of the same time every day, including weekends. Set an alarm for bedtime, not just wake time.",
        "timing": "Evening / Morning",
        "duration": "N/A",
        "frequency": "daily",
        "difficulty": 2,
        "mechanism": "Consistent sleep-wake timing reinforces circadian entrainment of the suprachiasmatic nucleus and peripheral clocks. Irregular schedules cause 'social jet lag' that disrupts cortisol rhythm, impairs glucose metabolism, and reduces sleep efficiency by fragmenting sleep architecture.",
        "expected_benefit": "Improved sleep efficiency, faster sleep onset, better subjective sleep quality, lower cardiometabolic risk, more stable mood and energy.",
        "contraindications": "Shift workers may need adapted strategies. Those with insomnia may benefit from sleep restriction therapy under guidance.",
        "sort_order": 1,
        "linked_pmids": ["20469800", "33054339"],
    },
    {
        "pillar_id": 3,
        "name": "Digital Sunset Protocol",
        "description": "Eliminate blue-light-emitting screens (phones, laptops, tablets) 60-90 minutes before target bedtime. Use dim, warm lighting. If screens are unavoidable, use blue-light filters at maximum strength.",
        "timing": "Evening (60-90 min before bed)",
        "duration": "60-90 min",
        "frequency": "daily",
        "difficulty": 2,
        "mechanism": "Blue light (460-480nm) suppresses pineal melatonin secretion in a dose-dependent manner via melanopsin receptor activation. Evening exposure delays the dim-light melatonin onset (DLMO) by 1.5-3 hours, shifting circadian phase and reducing sleep pressure at habitual bedtime.",
        "expected_benefit": "Earlier melatonin onset, reduced sleep latency, improved sleep quality, less nighttime awakenings, better next-day alertness.",
        "contraindications": "None. Those who rely on screens for work may use maximum-strength blue-light filters as a partial mitigation.",
        "sort_order": 2,
        "linked_pmids": ["27804960", "23691095"],
    },
    {
        "pillar_id": 3,
        "name": "Sleep Environment Optimization",
        "description": "Optimize bedroom for sleep: temperature 65-68F (18-20C), complete darkness (blackout curtains or eye mask), minimal noise (earplugs or white noise if needed), reserve bed for sleep only.",
        "timing": "Before bed",
        "duration": "N/A",
        "frequency": "daily",
        "difficulty": 1,
        "mechanism": "Core body temperature must drop 1-1.5C to initiate and maintain sleep. Cool ambient temperature facilitates thermoregulatory heat loss. Darkness prevents residual light-induced melatonin suppression. Stimulus control (bed = sleep only) strengthens the sleep-onset association via classical conditioning.",
        "expected_benefit": "Faster sleep onset, fewer awakenings, increased slow-wave sleep duration, improved next-day cognitive performance.",
        "contraindications": "Partners may have different temperature preferences. Earplugs may not be suitable if caring for young children.",
        "sort_order": 3,
        "linked_pmids": ["28889101", "27743803"],
    },
    {
        "pillar_id": 3,
        "name": "Caffeine Curfew (10h before bed)",
        "description": "Stop all caffeine intake at least 10 hours before your target bedtime. If bedtime is 10pm, last caffeine by 12pm noon. This includes coffee, tea, energy drinks, and dark chocolate.",
        "timing": "Morning only",
        "duration": "N/A",
        "frequency": "daily",
        "difficulty": 2,
        "mechanism": "Caffeine is a competitive adenosine receptor antagonist with a half-life of 5-7 hours (varies by CYP1A2 genotype). Even when subjectively unnoticed, caffeine consumed 6 hours before bed reduces total sleep time by ~40 minutes and decreases slow-wave (deep) sleep significantly.",
        "expected_benefit": "Improved sleep depth and duration, faster sleep onset, more restorative slow-wave sleep, reduced nighttime awakenings.",
        "contraindications": "Those with caffeine dependency should taper gradually to avoid withdrawal headaches. Not applicable to caffeine-free individuals.",
        "sort_order": 4,
        "linked_pmids": ["26140821", "20469800"],
    },
    # ══════════════════════════════════════════════════════════════════════════
    # PILLAR 4: STRESS MANAGEMENT
    # ══════════════════════════════════════════════════════════════════════════
    {
        "pillar_id": 4,
        "name": "Morning Mindfulness (10 min)",
        "description": "Practice 10 minutes of mindfulness meditation upon waking, before checking any devices. Focus on breath awareness, body scan, or open monitoring. Use guided apps if helpful.",
        "timing": "Morning",
        "duration": "10 min",
        "frequency": "daily",
        "difficulty": 1,
        "mechanism": "Mindfulness meditation activates the prefrontal cortex and reduces amygdala reactivity, lowering HPA axis activation. Regular practice increases gray matter density in areas associated with self-awareness, empathy, and emotional regulation. Reduces cortisol levels and pro-inflammatory cytokines.",
        "expected_benefit": "Reduced anxiety and perceived stress, improved emotional regulation, lower cortisol, enhanced focus and attention, improved immune function.",
        "contraindications": "Those with trauma history may prefer body-based practices over prolonged stillness. Guided sessions recommended for beginners.",
        "sort_order": 1,
        "linked_pmids": ["24395196", "25818837"],
    },
    {
        "pillar_id": 4,
        "name": "4-7-8 Breathing Reset",
        "description": "Practice the 4-7-8 breathing technique: inhale through nose for 4 counts, hold for 7 counts, exhale through mouth for 8 counts. Perform 4 cycles. Use before stressful situations, during work breaks, or before sleep.",
        "timing": "Anytime (2-3x daily)",
        "duration": "2-3 min",
        "frequency": "daily",
        "difficulty": 1,
        "mechanism": "Extended exhalation activates the parasympathetic nervous system via vagal afferents. The hold phase increases CO2 tolerance and engages the dive reflex. This shifts autonomic balance from sympathetic dominance to parasympathetic recovery, reducing heart rate and blood pressure within minutes.",
        "expected_benefit": "Immediate anxiety reduction, lower heart rate and blood pressure, improved vagal tone (HRV), better stress reactivity, faster recovery from acute stress.",
        "contraindications": "Those with respiratory conditions should adjust hold duration. Avoid the extended hold if lightheaded.",
        "sort_order": 2,
        "linked_pmids": ["35623448", "29697885"],
    },
    {
        "pillar_id": 4,
        "name": "Nature Exposure (20 min)",
        "description": "Spend at least 20 minutes in a natural environment: park, forest, garden, waterside, or tree-lined path. Walk slowly, sit, or practice gentle movement. Leave phone silent.",
        "timing": "Morning or Afternoon",
        "duration": "20-30 min",
        "frequency": "3-5x per week",
        "difficulty": 1,
        "mechanism": "Nature exposure reduces salivary cortisol, lowers sympathetic nerve activity, and decreases blood pressure. Phytoncides (volatile organic compounds from trees) enhance natural killer cell activity. Attention Restoration Theory: natural environments allow directed attention fatigue to recover.",
        "expected_benefit": "Reduced cortisol and stress hormones, lower blood pressure, improved mood and well-being, enhanced immune function, improved cognitive restoration.",
        "contraindications": "Sun protection for extended outdoor time. Be aware of allergens if applicable.",
        "sort_order": 3,
        "linked_pmids": ["28415916", "37585888"],
    },
    {
        "pillar_id": 4,
        "name": "Evening Gratitude Practice",
        "description": "Before bed, write down 3 specific things you are grateful for from the day. Be concrete and detailed rather than generic. Reflect on why each matters.",
        "timing": "Evening (before bed)",
        "duration": "5 min",
        "frequency": "daily",
        "difficulty": 1,
        "mechanism": "Gratitude journaling activates the ventromedial prefrontal cortex and hypothalamus, releasing dopamine and serotonin. Regular practice strengthens neural pathways for positive emotion processing, counteracting the negativity bias of the default mode network.",
        "expected_benefit": "Improved subjective well-being, better sleep quality, reduced depressive symptoms, enhanced prosocial behavior, greater life satisfaction.",
        "contraindications": "Those experiencing acute grief or trauma should not feel pressured. Adapt to acknowledge difficult emotions alongside gratitude.",
        "sort_order": 4,
        "linked_pmids": ["34646931", "15250815"],
    },
    {
        "pillar_id": 4,
        "name": "Progressive Muscle Relaxation",
        "description": "Systematically tense and release muscle groups from feet to face, holding tension for 5 seconds then relaxing for 15 seconds. Work through 8-12 muscle groups over 15-20 minutes.",
        "timing": "Evening or before bed",
        "duration": "15-20 min",
        "frequency": "3-5x per week",
        "difficulty": 1,
        "mechanism": "PMR reduces muscle spindle firing rate and sympathetic nervous system arousal via reciprocal inhibition. The tension-release cycle teaches discrimination between muscular tension and relaxation states, reducing baseline muscle tension and associated anxiety over time.",
        "expected_benefit": "Reduced muscle tension and pain, lower anxiety, improved sleep quality, reduced blood pressure, enhanced body awareness.",
        "contraindications": "Avoid tensing injured areas. Those with chronic pain may prefer passive relaxation techniques. Not recommended during muscle spasm.",
        "sort_order": 5,
        "linked_pmids": ["25818837", "28478782"],
    },
    # ══════════════════════════════════════════════════════════════════════════
    # PILLAR 5: SOCIAL CONNECTION
    # ══════════════════════════════════════════════════════════════════════════
    {
        "pillar_id": 5,
        "name": "Meaningful Conversation (15 min)",
        "description": "Have at least one meaningful, uninterrupted conversation per day. Put devices away, maintain eye contact, practice active listening. Move beyond surface-level small talk to genuine exchange.",
        "timing": "Anytime",
        "duration": "15+ min",
        "frequency": "daily",
        "difficulty": 1,
        "mechanism": "Substantive conversations activate mirror neuron systems and oxytocin release, strengthening social bonds. Deep listening engages mentalizing networks (medial prefrontal cortex, temporoparietal junction). Quality social interaction buffers the HPA axis stress response.",
        "expected_benefit": "Increased sense of belonging and well-being, reduced loneliness, lower cortisol, improved emotional processing, stronger relationships.",
        "contraindications": "Those with social anxiety may start with shorter, lower-pressure interactions and build gradually.",
        "sort_order": 1,
        "linked_pmids": ["20668659", "37337095"],
    },
    {
        "pillar_id": 5,
        "name": "Weekly Community Activity",
        "description": "Participate in one group activity per week that involves face-to-face interaction: sports team, volunteer work, religious/spiritual gathering, book club, class, hiking group, or shared hobby.",
        "timing": "Any day",
        "duration": "60+ min",
        "frequency": "1x per week",
        "difficulty": 2,
        "mechanism": "Group belonging satisfies fundamental psychological needs for relatedness and competence (Self-Determination Theory). Regular communal activities create predictable social contact, build social capital, and provide diverse relationship types that buffer against over-reliance on single relationships.",
        "expected_benefit": "Expanded social network, reduced isolation risk, improved purpose and belonging, lower cardiovascular risk associated with strong social integration.",
        "contraindications": "Those with agoraphobia or severe social anxiety may need professional support. Start with small, low-pressure groups.",
        "sort_order": 2,
        "linked_pmids": ["27091846", "17011690"],
    },
    {
        "pillar_id": 5,
        "name": "Digital Connection Ritual",
        "description": "Schedule one video or phone call per week with a friend or family member who lives far away. Set a recurring calendar event to maintain consistency.",
        "timing": "Anytime",
        "duration": "20-30 min",
        "frequency": "1-2x per week",
        "difficulty": 1,
        "mechanism": "Voice-based communication (phone/video) activates more social-cognitive neural circuits than text-based messaging. Hearing vocal prosody conveys emotional content that text cannot, facilitating empathy and emotional co-regulation even at a distance.",
        "expected_benefit": "Maintained long-distance relationships, reduced loneliness, sense of social support, emotional regulation through co-regulation.",
        "contraindications": "None significant. Respect time zones and boundaries of contact.",
        "sort_order": 3,
        "linked_pmids": ["25910392", "23421326"],
    },
    {
        "pillar_id": 5,
        "name": "Acts of Kindness Practice",
        "description": "Perform 2-3 deliberate acts of kindness per week: helping a neighbor, complimenting a stranger, volunteering time, writing an appreciation note, buying someone coffee.",
        "timing": "Anytime",
        "duration": "5-15 min each",
        "frequency": "2-3x per week",
        "difficulty": 1,
        "mechanism": "Prosocial behavior activates the mesolimbic reward pathway (ventral tegmental area, nucleus accumbens), producing a 'helper's high.' Altruistic actions increase oxytocin and reduce cortisol. Performing kindness strengthens social bonds bidirectionally via reciprocity norms.",
        "expected_benefit": "Increased happiness and life satisfaction, reduced depression, strengthened social bonds, improved self-esteem, potential longevity benefits.",
        "contraindications": "Avoid over-extending at the expense of self-care. Acts should be genuine, not performative.",
        "sort_order": 4,
        "linked_pmids": ["15250815", "30452410"],
    },
    # ══════════════════════════════════════════════════════════════════════════
    # PILLAR 6: SUBSTANCE AVOIDANCE
    # ══════════════════════════════════════════════════════════════════════════
    {
        "pillar_id": 6,
        "name": "Alcohol-Free Days (4+/week)",
        "description": "Maintain at least 4 alcohol-free days per week. On drinking days, limit to 1 standard drink (women) or 2 standard drinks (men). Track using the app.",
        "timing": "Evening",
        "duration": "N/A",
        "frequency": "daily",
        "difficulty": 2,
        "mechanism": "Alcohol disrupts sleep architecture (suppresses REM), impairs hepatic lipid metabolism, increases acetaldehyde-mediated DNA damage, and is classified as a Group 1 carcinogen by IARC. Even moderate consumption dose-dependently increases cancer risk. Alcohol-free days allow hepatic recovery and normalize sleep.",
        "expected_benefit": "Improved sleep quality, reduced cancer risk, better liver function, weight management, improved next-day cognitive performance.",
        "contraindications": "Those with alcohol use disorder should seek professional support rather than attempting moderation alone. Sudden cessation in heavy drinkers can be medically dangerous.",
        "sort_order": 1,
        "linked_pmids": ["30146330", "23347102"],
    },
    {
        "pillar_id": 6,
        "name": "Healthy Drink Swap",
        "description": "Replace one sugary or alcoholic drink per day with a healthier alternative: herbal tea, sparkling water with citrus, kombucha, or water with fruit/herb infusion.",
        "timing": "Anytime",
        "duration": "N/A",
        "frequency": "daily",
        "difficulty": 1,
        "mechanism": "Reducing added sugar from beverages lowers fructose-driven hepatic de novo lipogenesis, reduces insulin spikes, and decreases caloric intake without triggering compensatory hunger. Hydration with non-caloric beverages supports renal function and cognitive performance.",
        "expected_benefit": "Reduced caloric intake, improved hydration, lower triglycerides, better dental health, reduced metabolic disease risk.",
        "contraindications": "Those with caffeine sensitivity should choose caffeine-free herbal teas. Kombucha contains trace alcohol.",
        "sort_order": 2,
        "linked_pmids": ["37684424", "35333364"],
    },
    {
        "pillar_id": 6,
        "name": "Smoke-Free Commitment",
        "description": "If currently smoking, commit to a quit plan with a target date. If already smoke-free, note days since quitting. Use evidence-based cessation aids (NRT, varenicline) as appropriate.",
        "timing": "Anytime",
        "duration": "Ongoing",
        "frequency": "daily",
        "difficulty": 3,
        "mechanism": "Tobacco smoke contains 70+ carcinogens and damages endothelial function within hours. Nicotine hijacks the mesolimbic dopamine pathway creating powerful addiction. Evidence-based cessation combines behavioral strategies with pharmacotherapy (NRT, varenicline) for 2-3x higher quit rates.",
        "expected_benefit": "Within 20 min: heart rate drops. 1 year: CVD risk halved. 5-10 years: stroke and cancer risk approach non-smoker levels. 15 years: CHD risk equals non-smoker.",
        "contraindications": "Varenicline has psychiatric side effect warnings. NRT patches contraindicated in certain skin conditions. Always use under medical supervision.",
        "sort_order": 3,
        "linked_pmids": ["32803250", "17652652"],
    },
    {
        "pillar_id": 6,
        "name": "Substance-Free Socializing",
        "description": "Plan and attend at least one social event per week that does not center around alcohol or substance use: morning coffee dates, hiking, board game nights, fitness classes, museum visits.",
        "timing": "Any day",
        "duration": "60+ min",
        "frequency": "1x per week",
        "difficulty": 2,
        "mechanism": "Social identity theory shows that aligning with substance-free social groups changes self-concept and reduces relapse risk. Creating positive associations with substance-free activities builds new reward pathways and provides social support for behavior change.",
        "expected_benefit": "Reduced social triggers for substance use, expanded substance-free social network, new healthy habits and hobbies, maintained social connection without substances.",
        "contraindications": "Those in early recovery should avoid high-risk social environments. Professional support recommended for substance use disorders.",
        "sort_order": 4,
        "linked_pmids": ["26188829", "30758486"],
    },
]
