"""Wearable-driven 5-domain wheel configuration.

The scoring ranges below are pragmatic defaults for normalization and should be
customized per device ecosystem and individual baseline.
"""

WEARABLE_WHEEL_DOMAINS = {
    "heart_metabolism": {
        "name": "Heart & Metabolism",
        "short": "HM",
        "color": "#E53935",
        "icon": "heart_plus",
        "description": "Cardiorespiratory and activity load signals.",
        "is_proxy": False,
    },
    "muscle_bones": {
        "name": "Muscle & Bones",
        "short": "MB",
        "color": "#8D6E63",
        "icon": "fitness_center",
        "description": "Movement and load proxies from wearables.",
        "is_proxy": True,
    },
    "gut_digestion": {
        "name": "Gut & Digestion",
        "short": "GD",
        "color": "#43A047",
        "icon": "eco",
        "description": "Autonomic and sleep-linked proxy signals.",
        "is_proxy": True,
    },
    "brain_health": {
        "name": "Brain Health",
        "short": "BH",
        "color": "#5C6BC0",
        "icon": "neurology",
        "description": "Sleep architecture, debt, and restoration.",
        "is_proxy": False,
    },
    "system_wide": {
        "name": "System Wide (Hormone Incl.)",
        "short": "SW",
        "color": "#00897B",
        "icon": "monitor_heart",
        "description": "Whole-system stress and recovery physiology.",
        "is_proxy": False,
    },
}

DOMAIN_ORDER = [
    "heart_metabolism",
    "muscle_bones",
    "gut_digestion",
    "brain_health",
    "system_wide",
]


# Metric scoring modes:
# - higher_better
# - lower_better
# - target_band
# - binary
#
# Optional:
# - transform="abs" (applies abs(value) before scoring)
WEARABLE_METRIC_SPECS = {
    # Heart & Metabolism (HM)
    "arrhythmia_alert_afib": {
        "label": "Arrhythmia Alert (AFib)",
        "unit": "flag",
        "score_mode": "binary",
        "healthy_value": 0,
        "domain": "heart_metabolism",
        "weight": 1.2,
    },
    "average_heart_rate_bpm": {
        "label": "Average Heart Rate",
        "unit": "bpm",
        "score_mode": "target_band",
        "hard_min": 40,
        "optimal_min": 55,
        "optimal_max": 75,
        "hard_max": 95,
        "domain": "heart_metabolism",
    },
    "heart_rate_variability_ms": {
        "label": "Heart Rate Variability",
        "unit": "ms",
        "score_mode": "higher_better",
        "min_value": 15,
        "max_value": 90,
        "domain": "heart_metabolism",
        "weight": 1.2,
    },
    "maximum_heart_rate_bpm": {
        "label": "Maximum Heart Rate",
        "unit": "bpm",
        "score_mode": "target_band",
        "hard_min": 90,
        "optimal_min": 125,
        "optimal_max": 185,
        "hard_max": 210,
        "domain": "heart_metabolism",
        "weight": 0.8,
    },
    "respiratory_rate_bpm": {
        "label": "Respiratory Rate",
        "unit": "breaths/min",
        "score_mode": "target_band",
        "hard_min": 8,
        "optimal_min": 12,
        "optimal_max": 18,
        "hard_max": 24,
        "domain": "heart_metabolism",
    },
    "resting_heart_rate_bpm": {
        "label": "Resting Heart Rate",
        "unit": "bpm",
        "score_mode": "target_band",
        "hard_min": 38,
        "optimal_min": 45,
        "optimal_max": 65,
        "hard_max": 90,
        "domain": "heart_metabolism",
        "weight": 1.2,
    },
    "steps_count": {
        "label": "Steps",
        "unit": "steps",
        "score_mode": "higher_better",
        "min_value": 2000,
        "max_value": 12000,
        "domain": "heart_metabolism",
        "weight": 1.0,
    },
    "kilojoule_expended": {
        "label": "Kilojoule Expended",
        "unit": "kJ",
        "score_mode": "higher_better",
        "min_value": 700,
        "max_value": 3200,
        "domain": "heart_metabolism",
        "weight": 0.9,
    },

    # System Wide (SW)
    "body_temperature_deviation_c": {
        "label": "Body Temperature Deviation",
        "unit": "C",
        "score_mode": "lower_better",
        "min_value": 0.0,
        "max_value": 1.5,
        "transform": "abs",
        "domain": "system_wide",
        "weight": 1.0,
    },
    "overnight_spo2_avg_pct": {
        "label": "Overnight SpO2 Avg",
        "unit": "%",
        "score_mode": "higher_better",
        "min_value": 90,
        "max_value": 99,
        "domain": "system_wide",
        "weight": 1.1,
    },
    "overnight_spo2_nadir_pct": {
        "label": "Overnight SpO2 Nadir",
        "unit": "%",
        "score_mode": "higher_better",
        "min_value": 85,
        "max_value": 97,
        "domain": "system_wide",
        "weight": 1.0,
    },
    "recovery_score": {
        "label": "Recovery Score",
        "unit": "score",
        "score_mode": "higher_better",
        "min_value": 0,
        "max_value": 100,
        "domain": "system_wide",
        "weight": 1.2,
    },
    "skin_temperature_c": {
        "label": "Skin Temperature",
        "unit": "C",
        "score_mode": "target_band",
        "hard_min": 30.0,
        "optimal_min": 32.0,
        "optimal_max": 35.0,
        "hard_max": 37.0,
        "domain": "system_wide",
        "weight": 0.8,
    },
    "spo2_pct": {
        "label": "SpO2",
        "unit": "%",
        "score_mode": "higher_better",
        "min_value": 90,
        "max_value": 100,
        "domain": "system_wide",
        "weight": 1.0,
    },

    # Brain Health (BH)
    "baseline_sleep_needed_hours": {
        "label": "Baseline Sleep Needed",
        "unit": "hours",
        "score_mode": "target_band",
        "hard_min": 5.0,
        "optimal_min": 7.0,
        "optimal_max": 9.0,
        "hard_max": 11.0,
        "domain": "brain_health",
        "weight": 0.8,
    },
    "number_of_naps": {
        "label": "Number of Naps",
        "unit": "count",
        "score_mode": "lower_better",
        "min_value": 0,
        "max_value": 4,
        "domain": "brain_health",
        "weight": 0.5,
    },
    "sleep_consistency_pct": {
        "label": "Sleep Consistency",
        "unit": "%",
        "score_mode": "higher_better",
        "min_value": 50,
        "max_value": 100,
        "domain": "brain_health",
        "weight": 1.2,
    },
    "sleep_cycle_count": {
        "label": "Sleep Cycle Count",
        "unit": "cycles",
        "score_mode": "target_band",
        "hard_min": 2,
        "optimal_min": 4,
        "optimal_max": 6,
        "hard_max": 8,
        "domain": "brain_health",
        "weight": 0.9,
    },
    "sleep_debt_hours": {
        "label": "Sleep Debt",
        "unit": "hours",
        "score_mode": "lower_better",
        "min_value": 0,
        "max_value": 8,
        "domain": "brain_health",
        "weight": 1.2,
    },
    "sleep_disturbance_count": {
        "label": "Sleep Disturbance Count",
        "unit": "count",
        "score_mode": "lower_better",
        "min_value": 0,
        "max_value": 12,
        "domain": "brain_health",
        "weight": 1.0,
    },
    "sleep_efficiency_pct": {
        "label": "Sleep Efficiency",
        "unit": "%",
        "score_mode": "higher_better",
        "min_value": 70,
        "max_value": 98,
        "domain": "brain_health",
        "weight": 1.3,
    },
    "sleep_latency_min": {
        "label": "Sleep Latency",
        "unit": "min",
        "score_mode": "target_band",
        "hard_min": 0,
        "optimal_min": 10,
        "optimal_max": 20,
        "hard_max": 60,
        "domain": "brain_health",
        "weight": 0.9,
    },
    "sleep_needed_from_recent_nap_min": {
        "label": "Sleep Needed from Recent Nap",
        "unit": "min",
        "score_mode": "lower_better",
        "min_value": 0,
        "max_value": 120,
        "domain": "brain_health",
        "weight": 0.6,
    },
    "sleep_needed_from_recent_strain_min": {
        "label": "Sleep Needed from Recent Strain",
        "unit": "min",
        "score_mode": "lower_better",
        "min_value": 0,
        "max_value": 240,
        "domain": "brain_health",
        "weight": 0.8,
    },
    "sleep_performance_pct": {
        "label": "Sleep Performance",
        "unit": "%",
        "score_mode": "higher_better",
        "min_value": 50,
        "max_value": 100,
        "domain": "brain_health",
        "weight": 1.2,
    },
    "total_awake_time_min": {
        "label": "Total Awake Time",
        "unit": "min",
        "score_mode": "lower_better",
        "min_value": 0,
        "max_value": 120,
        "domain": "brain_health",
        "weight": 1.0,
    },
    "total_light_sleep_time_min": {
        "label": "Total Light Sleep Time",
        "unit": "min",
        "score_mode": "target_band",
        "hard_min": 60,
        "optimal_min": 180,
        "optimal_max": 300,
        "hard_max": 420,
        "domain": "brain_health",
        "weight": 0.7,
    },
    "total_no_sleep_data_received_time_min": {
        "label": "Total No Sleep Data Received Time",
        "unit": "min",
        "score_mode": "lower_better",
        "min_value": 0,
        "max_value": 60,
        "domain": "brain_health",
        "weight": 0.6,
    },
    "total_rem_sleep_time_min": {
        "label": "Total REM Sleep Time",
        "unit": "min",
        "score_mode": "target_band",
        "hard_min": 30,
        "optimal_min": 80,
        "optimal_max": 130,
        "hard_max": 220,
        "domain": "brain_health",
        "weight": 1.0,
    },
    "total_slow_wave_sleep_time_min": {
        "label": "Total Slow Wave Sleep Time",
        "unit": "min",
        "score_mode": "target_band",
        "hard_min": 20,
        "optimal_min": 60,
        "optimal_max": 120,
        "hard_max": 220,
        "domain": "brain_health",
        "weight": 1.0,
    },
    "total_time_spent_in_bed_min": {
        "label": "Total Time Spent in Bed",
        "unit": "min",
        "score_mode": "target_band",
        "hard_min": 300,
        "optimal_min": 420,
        "optimal_max": 540,
        "hard_max": 720,
        "domain": "brain_health",
        "weight": 0.8,
    },
}


DIRECT_DOMAIN_METRICS = {
    "heart_metabolism": [
        "arrhythmia_alert_afib",
        "average_heart_rate_bpm",
        "heart_rate_variability_ms",
        "maximum_heart_rate_bpm",
        "respiratory_rate_bpm",
        "resting_heart_rate_bpm",
        "steps_count",
        "kilojoule_expended",
    ],
    "system_wide": [
        "body_temperature_deviation_c",
        "overnight_spo2_avg_pct",
        "overnight_spo2_nadir_pct",
        "recovery_score",
        "skin_temperature_c",
        "spo2_pct",
    ],
    "brain_health": [
        "baseline_sleep_needed_hours",
        "number_of_naps",
        "sleep_consistency_pct",
        "sleep_cycle_count",
        "sleep_debt_hours",
        "sleep_disturbance_count",
        "sleep_efficiency_pct",
        "sleep_latency_min",
        "sleep_needed_from_recent_nap_min",
        "sleep_needed_from_recent_strain_min",
        "sleep_performance_pct",
        "total_awake_time_min",
        "total_light_sleep_time_min",
        "total_no_sleep_data_received_time_min",
        "total_rem_sleep_time_min",
        "total_slow_wave_sleep_time_min",
        "total_time_spent_in_bed_min",
    ],
}


# Proxy-only domains until dedicated wearable metrics are integrated.
PROXY_DOMAIN_WEIGHTS = {
    "muscle_bones": {
        "steps_count": 0.45,
        "kilojoule_expended": 0.35,
        "recovery_score": 0.20,
    },
    "gut_digestion": {
        "sleep_efficiency_pct": 0.35,
        "respiratory_rate_bpm": 0.20,
        "heart_rate_variability_ms": 0.25,
        "body_temperature_deviation_c": 0.20,
    },
}


CSV_TEMPLATE_HEADER = [
    "metric_code",
    "value",
    "measured_at",
    "source",
]

